h4cc/awesome-elixir

README.md
Added expcap library (which is available on hex.pm) to the networking section.
=> adding expcap library

README.md
Add a link to a screencast by José Valim.
=> add Meet Elixir Screencast by José Valim

README.md
Hi there! Just published a package for Bitcoin's Base58Check. Hope others will find it useful!
=> Base58Check for Bitcoin

README.md
I haven't added this library to hex.pm yet, but I plan to once I get a full release version.
=> Add repeatex library

README.md
...and also a small newline fix
=> vim-elixir

README.md
MessagePack (de)serializer implementation for Elixir.
=> Add msgpax library

README.md
Closes  #332, #325, #318.
I can squash these commits into one if preferred.
=> http_router, pool, mandrill

README.md
=> Add GoodTimes

README.md
I'm not sure this counts as awesome yet but I thought I'd open the discussion :-)
=> Add white_ bread BDD to testing section

README.md
We had trouble with exredis and connecting to secure redis instances. 
Heroku supports this. And its good.
=> Adding redo

README.md
Add a new module [chinese_translation](https://github.com/tyrchen/chinese_translation).
=> add chinese_translation module

README.md
=> Added zarex

README.md
I've seen many times a questions on IRC regarding several topics that I hope this small application highlights:
* basic usage of `GenServer` and `GenEvent` (and their testing)
* IO lists (and `IO.ANSI` usage)
* building of an escript for the project
* probably something more (like Ports)
=> Add tty2048 application

README.md
=> Added librex

README.md
=> Add PlugRequireHeader

README.md
Resolves [#427](https://github.com/h4cc/awesome-elixir/issues/427)
=> [427] Add Package cobertura_cover

README.md
=> add world_json to JSON category - #missing full stop - #458

README.md
@h4cc just thought that putting it to Utilities instead of Miscellaneous would be better. What do you think?
=> add new Utilities category and added exjprop to it - #425

README.md
Added Elixir Cookbook to Resources/Books section.
=> Added Elixir Cookbook.

README.md
I added a link to my Atom package that lets a user run and interact with an IEx session in Atom.
=> Added atom-iex link

README.md
First and foremost, thanks for this awesome resource; awesome-elixir is my goto.
I noticed you had a number of Issues opened so I thought I would try and lend a hand.  This PR closes #631.
Thanks again! :+1:
=> Add aws to Cloud Infrastructure and Management

README.md
Good morning @h4cc, I thought I would start off Friday with another addition to your awesome repo.  This time I made sure I used a dash :grinning: 
This closes #607
Thanks again.
=> Add slacker to Networking

README.md
=> Add scaffold library

README.md
Added `sqlite_ecto` to "ORM and Datamapping". 
Closes #619
=> Add sqlite_ecto

README.md
Add telephonist, ar2ecto, and mon_handler.  This closes #623, #624, #625.
=> A few additions

README.md
RFC @h4cc — This closes #617, #618, #620, #628, and #629.  I cannot find resources for the remaining open issues or I would have included those.
Thanks again this :+1:
=> More awesome libraries

README.md
Hi @h4cc, I pulled this one out into a separate PR since it doesn't currently exist as an issue.  This adds [Elixir Experience](http://elixirexperience.com/) to the Reading section.
=> Add Elixir Experience.

README.md
Hey @h4cc -- hopefully I did this right!
Love this repo :)
=> Adding neotomex, a PEG implementation

README.md
Hi @h4cc, this includes two libraries and one resource.  As such, it closes #644 and #645.
=> Awesome additions

README.md
This closes #650, #651, #652 and #653.
=> Newest additions

README.md
Howdy @h4cc, hope all is well.  Here are a few additional entries.  This PR closes #660, #659, and #655.
=> More entries

README.md
- Add Weebo, closes #664.
- Add Elixir School, closes #665.
- Add Gimei_ex, closes #666.
=> Add Elixir School, gimei_ex, weebo.

README.md
https://github.com/rwdaigle/metrix
=> Add metrix

README.md
Elixir Job Board relaunch. Please re-add.
=> Re-adding elixir job board

README.md
Sorry for some reason, my brain sorts ex before elixir.
=> Added a reference to elixgrep project

README.md
=> Add plug_ribbon

README.md
=> Fix typo genarator → generator

README.md
=> Added pdf2htmlex

README.md
Thanks for this project, Julius.
=> Add Lighthouse Scheme.

README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/h4cc/awesome-elixir/824)
=> Added figaro_elixir

README.md
Hi @h4cc, this PR adds a couple of the libraries from Issues: #749, #752, #754, #765, #767, #769, #772.
=> New libraries

README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/h4cc/awesome-elixir/832)
=> Added YAML parser for elixir

README.md
=> Add stevegraham/hypermock

README.md
Self-generating modules and unit tests to save some time when coding `Mix` projects is the idea of this vim plugin.
=> Add vim plugin elixir_generator

README.md
=> Add Package "nadia"

README.md
> "If I had a dime for every time I've seen someone use FLOAT to store currency, I'd have $999.997634" -- Bill Karwin
In short: You shouldn't represent monetary values by a float or decimal. Wherever you need to represent money, use this Money :+1:
=> adding money

README.md
=> Add Package "tfidf"

README.md
Hi @h4cc, this adds `slim_fast`, `json_web_token_ex`, and `yocingo`.
=> Add three new libraries

README.md
Adds the two packages, therefore fixing #847 and #849 :grinning:
=> Add haikunator and phoenix_html_sanitizer

README.md
A package for MS Excel parsing
=> Add excellent

README.md
=> adds bitmap hex package to algorithms and data structure section

README.md
https://github.com/h4cc/awesome-elixir/issues/971
=> add ex_parametarized

README.md
Just FWIW this is a full implementation of the API ;)
closes #1036
=> added Elixtagram under Third Party APIs

README.md
=> Add Cloak package to Cryptography

README.md
Docs: http://hexdocs.pm/gcmex/0.0.1/
Link: https://hex.pm/packages/gcmex
=> add gcmex packages

README.md
vulvapi and vulvex are dead links. All three are not awesome.
=> Remove vulvapi, vulvex, dicks

README.md
Wasn't sure whether to create a new section for this (Podcasts) so I simply added it to the existing "Websites" section.
=> Add "Elixir Fountain" to the list of websites

README.md
This commit adds ExMachina to the "Testing" section
=> Add ExMachina

README.md
This adds [LearnElixir.tv](https://www.learnelixir.tv/) to "Screencasts".
=> Add LearnElixir.tv

README.md
Add IElixir to the list of "Cloud Infrastructure and Management"
=> Add IElixir to the list

README.md
Add embedded systems section and Nerves Project.
=> Add nerves

README.md
#1202 
Add Witchcraft to "Algorithms and Data structures"
=> Add Witchcraft

README.md
Closes #1236, #1233, #1232, #1244, and #1246.
=> Add Ueberauth and strategies

README.md
fix typo regarding library name
=> fix typo against ex_parameterized

README.md
Fix issue: Add Package "mandrake" #1326
=> Add library "mandrake"

README.md
Closes "#964 - Add Package `apns`".
=> apns4ex added

README.md
#1346 
Add `distance_api_matrix` to `Geolocation`
=> Add distance_api_matrix

README.md
Went through issues 1333 through 1361 and added the respective libraries to the `README`:
fixes #1361
fixes #1360
fixes #1359
fixes #1358
fixes #1357
fixes #1356
fixes #1355
fixes #1354
fixes #1352
fixes #1351
fixes #1350
fixes #1349
fixes #1347
fixes #1345
fixes #1344
fixes #1342
fixes #1341
fixes #1340
fixes #1339
fixes #1338
fixes #1337
fixes #1336
fixes #1333
=> Fix issues 1333-1361

README.md
Please accept the addition of monetized which is a library I wrote for handling money. It takes a different approach to the existing 'money' library and will have continued development and maintenance from myself.
Thanks
=> added monetized

README.md
=> Add siphash-elixir

README.md
Closes #1023 Add Package "power_assert"
=> add power_assert

README.md
The other exif library (exexif) hasn't been updated in a very long time and does not work, so I made a new one.
=> Added ElixirExif

README.md
=> adding couchdb_connector

README.md
=> Add exfile

README.md
"An Elixir app which generates text-based tables for display".
Added it to the command-line section as that is the largest use case for the generated tables.
Closes #1438.
=> Add table_rex

README.md
https://github.com/h4cc/awesome-elixir/issues/1537
=> Added elixir_nsq to Queue section.

README.md
=> Add omise package

README.md
vim-ex_test allows you quickly run ExUnit tests from within Vim
Easy integration with tpope's dispatch work for async vim friendly TDD
=> Adding vim-ex_test to the editors

README.md
This resolves https://github.com/h4cc/awesome-elixir/issues/1229.
=> added Fuzzyurl to HTTP section

README.md
I was perusing the repo this morning and noticed this and figured I'd read over everything and see if I spotted anything else that I noticed (I didn't) and PR with a quick fix. Thanks for all the great work and let me know if I didn't submit this properly :) :+1:
=> Minor Typo/Grammar Fix

README.md
Add `ex_marshal` to `Protocols` section.
=> Add `ex_marshal`

README.md
Hey @h4cc, I'm the owner of this library on hex and wanted to help close #1423.
=> Add "filtrex" to "Date & Time" section

README.md
=> Add pipe_here

README.md
=> Add comeonin_ecto_password

README.md
=> Added exromaji library for translating

README.md
Add Plasm to the Utilities section
=> Add Plasm to the Utilities section

README.md
Moving to more appropriate section.
=> Move [paratize] to Algorithms and Data structures section.

README.md
https://github.com/h4cc/awesome-elixir/issues/1548
=> Add [combination]

README.md
close https://github.com/h4cc/awesome-elixir/issues/1491
_Elixir Experience_ is not found. So, I remove it additionally.
=> add revision_plate_ex and remove not found link

README.md
=> Add params

README.md
=> Add xe package

README.md
https://github.com/h4cc/awesome-elixir/issues/1163
=> Add [minmaxlist]

README.md
I just realized we have a style guide section here so I added Credo's style guide. :tada: 
We could potentially also add lexmag's personal style guide to this section, while we are collecting different views on this.
=> Add Credo's style guide

README.md
Stash is a small and user-friendly binding around Erlang Term Storage for Elixir.
Resolves #1697
=> Added stash

README.md
closes https://github.com/h4cc/awesome-elixir/issues/1732
=> Add extripe

README.md
=> Add Artifact & Hydra

README.md
=> Add Onetime and Fwatch

README.md
=> Add Package "sentient"

README.md
This resource is not related with Elixir.
=> No longer related with Elixir programming language

README.md
Added a link for elixir-sparkpost to the awesomeness!
=> Add SparkPost Elixir library

README.md
New Additions
+ Scrivener.Headers
+ Scrivener.HTML, closes #912
Updates
+ Elixir School link
=> A few updates

README.md
A simple Gmail REST API client for Elixir.
=> elixir-gmail

README.md
ExGuard is a mix command to handle events on file system modifications,
inspired by Ruby's Guard.
=> Added ex_guard

README.md
[ex_unit_notifier](https://github.com/navinpeiris/ex_unit_notifier) sends desktop notification for ExUnit tests.
=> Added ex_unit_notifier - Notifications for ExUnit

README.md
[Elixir Recipes](http://elixir-recipes.github.io) is a collection of patterns & solutions to common problems in Elixir.
=> Added Elixir Recipes

README.md
This PR adds 'Ratio', a package that allows creation of and perform arithmetic with Rational Numbers.
=> Adds 'Ratio' to Algorithms & Data Structures.

README.md
Add IP2Location library to Geolocation category.
=> Add IP2Location to Geolocation

README.md
Added exrm_deb and exrm_docker. I am not the author of exrm_deb, but thought I'd add it as well.
This also fixes https://github.com/h4cc/awesome-elixir/issues/1865
=> Add exrm_deb and exrm_docker

README.md
Link: https://hex.pm/packages/alchemic_avatar
Description:
Generate letter avatar from string
=> Add the Package "alchemic_avatar"

README.md
Added Bankster, a IBAN account number and BIC validation library
=> Added Bankster package

README.md
extracting and curating article from web page
=> Add Readability

README.md
=> Added exldap to Miscellaneous

README.md
Cachex is a powerful caching library with a wide variety of features.
=> Added Cachex to the Caching section

README.md
Segment-segment intersection classifier and calculator.
Github: https://github.com/pkinney/segseg_ex
Hex: https://hex.pm/packages/seg_seg
Docs: https://hexdocs.pm/seg_seg/SegSeg.html
Travis: https://travis-ci.org/pkinney/segseg_ex
=> Add `segseg` to the Geolocation section

README.md
https://github.com/sivsushruth/consolex
=> Add Consolex to applications category

README.md
Built that a while ago and completely forgot to add it here.
I feel like it has its place in this section but let me know if that's not the case.
=> Add Elixir Playground

README.md
=> Add seetconfig

CONTRIBUTING.md, README.md
with libraries related to neural network.
=> Add an Artificial Intelligence Category

README.md
=> Fix resources order

README.md
#766
not sure if it's under `Actors`
=> Add Package "dflow"

README.md
=> Added dublin_bus_api

README.md
Fixes https://github.com/h4cc/awesome-elixir/issues/2061
=> Added hypex

README.md
=> Added japan_municipality_code

README.md
Close issue https://github.com/h4cc/awesome-elixir/issues/2045
=> Add elixir_ipgeobase

README.md
Fixes #2079
I'm sorry, I added the package in the wrong place. It doesn't treat Date/Time...
=> Issues 2079

README.md
Hi,
I built a simple markov chain in elixir so I can learn the language better.
This PR adds it under "Examples / Funny Stuff"
=> Add Elixir Markov Chain to Examples/Funny Stuff

README.md
=> Adding pop3mail

README.md
=> Fixed the ordering

README.md
Used for server-side rendering of JS.
=> Added std_json_io

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, README.md
This adds an issue and pr template so we can have a default format of contributions and also improve the contribution guidelines with some more info.
=> Improve contributing

README.md
=> Added dot-notes

README.md
Added [Woolly](https://github.com/pjhampton/woolly) to the Natural Language Processing section.
=> Added Woolly to the NLP Section.

README.md
Weibo is the Chinese equivalent of Twitter in China.
=> Added Weibo OAuth2 Strategy

README.md
=> Add Package "ex_bcrypt".

README.md
=> Add "gen_state_machine"

README.md
"Awesome Elixir @LibHunt" is based on the github list plus ordering by popularity and some helpful metadata like dev activity. Moreover, it adds the option to compare different libs from the same category.
=> Add 'Awesome Elixir @LibHunt' to the Websites section

README.md
=> Introduce Benchmarking category + add benchee

README.md
This PR just contains a couple of changes to the projects I maintain - Comeonin and Openmaize.
The links and descriptions have been updated, and I've moved Openmaize to a 'Authentication' (from 'Authorization').
=> Updated riverrun repositories

README.md
=> Added pigeon.

README.md
Adding plug_secex. Closes #2368
=> adding plug_secex

README.md
=> add egaugex

README.md
=> add http_digex

README.md
=> Add simhash

README.md
=> Add ecto_factory

README.md
I was separating this:https://github.com/h4cc/awesome-elixir/pull/2302
- phoenix_html_simplified_helpers - Some helpers for phoenix html( truncate, time_ago_in_words, number_with_delimiter )
Thanks.
=> added added-phoenix_html_simplified_helpers

README.md
I was separating this:https://github.com/h4cc/awesome-elixir/pull/2302
- sitemap - Sitemap is the easiest way to generate Sitemaps in Elixir.
Thanks.
=> added sitemap

README.md
I haven't seen state machine implementation for ecto before. I think it'll be helpful
=> Add ecto_state_machine

README.md
=> Add Package "eliver"

README.md
=> Add Package "test_that_json"

README.md
Resolves https://github.com/h4cc/awesome-elixir/issues/2481
=> Add Package "Airbax"

README.md
=> Added `stemmer`

README.md
=> Added simple_bayes

tests/mix.lock
As discussed in #2293 as a separate PR
=> mix.lock update for new hex version

README.md
Remove dups and modify redirects from the awesome-bot report
=> Awesome-bot cleanup

README.md
Doesn't resolve an issue as I filed it the moment I pushed to Hex and the issue hasn't been picked up yet :)
=> Add sentix

README.md
Add Package "geohash"
Resolves #1156
=> Add Geohash to Geolocation list

README.md
=> Add navigation_tree

README.md
=> Add plug_fprof

README.md
=> Add semver

README.md
=> Add apostle

README.md
=> Add crypto_rsassa_pss

README.md
##Title
Add Package "govtrack"
##Description
Resolves "#2600"
Add govtrack
=> add govtrack

README.md
=> Add editor extension vscode-elixir

README.md
I know this probably doesn't fit pull request template, but I'm not adding new package here :innocent:
=> Rename ssl_verify_hostname to ssl_verify_fun. Also link fix.

README.md
##Title
Add Package "oceanex"
##Description
Resolves #2647
Add oceanex
=> Add oceanex

README.md
=> Add Package "digitalocean"

README.md
https://github.com/Nebo15/multiverse
=> Add Package "multiverse"

README.md
=>  Add Package "proj"

README.md
Added a BSON section with following package:
https://github.com/Nebo15/bsoneach
Maybe we need additionally add:
- https://github.com/checkiz/elixir-bson
=> Add Section "BSON" \ Add Package "bsoneach"

README.md
Add Package "exlager"
##Description
Elixir binding for lager
Add Package exlager
=> Add exlager

README.md
=> Add Package "exfacebook"

README.md
=> Add Package "data_morph"

README.md
##Title
Add Package `plug_rest`
##Description
Resolves "#2434"
Add plug_rest
Resolves #2434
=> Add Package "plug_rest"

README.md
##Description
Resolves "#2694"
Add phoenix_swagger
=> Add Package phoenix_swagger

README.md
[canada github link](https://github.com/jarednorman/canada/)
works with the latest elixir too. 😄
=> Add canada to authorization section

README.md
Adding https://github.com/timberio/key-value-parser-elixir
=> Add Timber.io's key_value_parser

README.md
Added Package "aescmac". It has (working) unit tests and works.
=> added aescmac package

README.md
=> Add Package particle

README.md
=> Add Package Honeywell

README.md
=> Add Package "Trans"

README.md
=> Add Package ui_faces

README.md
=> Add Package "retry"

README.md
=> Add Package "numerix"

README.md
=> Add Package "thumbnex"

README.md
=> Add Package "exop"

README.md
##Title
Add Package "paasaa"
##Description
Natural language detection for Elixir.
Adds the package `pasaa` - natural language detection for Elixir.
=> Add Package "paasaa"

README.md
=> Add Package "SMPPEX"

README.md
Add Package "kafka_consumer"
Resolves "#2823"
=> Add Package "KafkaConsumer"

README.md
`geoip`: Find geo location information given an IP address, hostname or Plug.Conn
=> Add Package `geoip`

README.md
=> Add Package "ecto_shortcuts"

README.md
=> Add Package "ffmpex"

README.md
Resolves #2773 
Also created new section for error & exception handling, duplicating entries that fall into this category.
=> Add Package "exceptional"

README.md
=> Add Package "silent_video"

README.md
Add Package "rsa_ex"
Resolves "#2827"
=> add package "RsaEx"

README.md
Move some deployment libraries to the new Deployment section
=> Move libraries to Deployment section

README.md
=> Add Package "Confex"

README.md
Resolves #2248
Add BlakeWilliams/doorman package to Authentication list.
=> Add Package BlakeWilliams/doorman

README.md
=> Add package RBMQ

README.md
Add Package "faker_elixir"
Add faker_elixir
=> Add faker_elixir to the readme

README.md
=> Add Package pipe_to

README.md
=> Add Package "bodyguard"

README.md
=> Add package "dnsimple"

README.md
Adds SublimeText plugin to options under editors.
I noticed there were not any options listed for SublimeText so I added one that
have been both useful and recommended.
Add elixir-tmbundle
=> Add elixir-tmbundle to editor options

README.md
=> Add Package "filterable"

README.md
=> Add Package "ignorant"

README.md
##Title
##Description
Resolves "#task-number"
=> feat: adding new testing library exkorpion

README.md
=> Add Package "dataframe"

README.md
=> add package 'tg_client'

README.md
Elixir-friendly [Prometheus.io](https://prometheus.io) monitoring system and time series database client
close #2728
=> Add Prometheus.ex

README.md
Simple elixir wrapper for Riak CS API
=> Add Package "ExRiakCS

README.md
Add Package "named_args"
Adds named arguments like feature to Elixir
=> Add named_args package

README.md
Adds [River](https://github.com/peburrows/river).
Resolves #2760.
=> Add Package "river"

README.md
Adds SublimeText plugin to options under editors.
I noticed there were few options listed for SublimeText so I added another one that
has been both useful and recommended.
Add ElixirSublime
=> Add ElixirSublime to editor options

README.md
OS Process Information Collector
closes #2546
=> Add prometheus_process_collector

README.md
=> Add Package darkskyx

README.md
=> Add Package ex_codesihp

README.md
=> Add Package "appsignal-elixir"

README.md
Add new entry to category:books for Elixir's Getting Started Guide in EPUB, MOBI, and PDF formats.
=>  Add Elixir's Getting Started Guide

README.md
Add Package [kitto](https://hex.pm/packages/kitto)
Resolves #2057
Kitto is a dashboard for interactive dashboards leveraging Server-Sent
Events and React widgets.
=> Add Kitto (#2057)

README.md
##Title
Add Package `ex_postmark`
##Description
Resolves #3165
Add ex_postmark email library
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h4cc/awesome-elixir/3165)
=> Add ex_postmark email library

README.md
Prometheus.io Phoenix integration
closes #2713
=> Add prometheus_phoenix

README.md
=> Fix spelling mistake in the package description

README.md
Ecto instrumenter for prometheus.ex
=> Add prometheus-ecto

README.md
=> Add Package "notifier"

README.md
Adds [sift_ex](https://github.com/C404/sift_ex)
Resolves #3118
=> Add Package "sift_ex"

README.md
=> Add elixir-browser

README.md
=> Add package sentry-elixir

README.md
=> Add Package "new_relic"

README.md
=> Add Package "geohax"

README.md
Resolves "#2860"
Resolves "#2966"
=> Add packages `commanded` and `eventsourced`

README.md
Resolves "#3295"
Resolves "#2875"
=> Add Package "arbor" and "apocryphal"

README.md
[countriex](https://github.com/navinpeiris/countriex) - A pure elixir country data provider containing various information for every country in ISO 3166.
=> Adding package "countriex"

README.md
=> Add Package "nvim"

README.md
* Update link for the main Elixir Style Guide (new maintainer)
* Add @lexmag's style guide
=> Update style guide links

README.md
Repo itself: https://github.com/veelenga/dress
=> Add Package "dress"

README.md
=> Add Package "ecto_mnesia"

README.md
=> Add Package "ecto_paging"

README.md
=> Add Package "skycluster"

README.md
##Title
Add Package "cassandra_ecto"
##Description
New pull request
Add cassandra_ecto
=> Add cassandra_ecto

README.md
=> Add Package "tiny"

README.md
=> Add Package "vessel"

README.md
Removing my own package which isn't really maintained and isn't very useful.
=> remove my own package

README.md
Adds library image64 
##Description
Resolves #2491
Added image64 library
=> Added image64 library

README.md
=> Add package "crontab"

README.md
=> Add Package "Qex"

README.md
=> Add Package Cronex

README.md
Resolves "#3029"
Add libcluster
=> Added libcluster

README.md
=> add package ex_mustang

README.md
=> Add Package Chemistry

README.md
The crontab package was relocated.
=> Correct package "crontab"

README.md
##Bolt.Sips
Add Package Bolt.Sips
##Description
A Neo4j driver for Elixir, using the Bolt protocol (Neo4j's newest network protocol, designed for high-performance)
Add Bolt.Sips
=> added Bolt.Sips

README.md
##Molasses
Add Package "molasses"
##Description
Resolves #3424
Add molasses
=> Adds molasses

README.md
=> Add Package protox

README.md
##Title
Add Package "dockerex"
##Description
Resolves "#2710"
Add Dockerex
=> Add Dockerex

README.md
=> Add Package "nimble_csv"

README.md
=> Add timelier.

README.md
Resolves https://github.com/h4cc/awesome-elixir/issues/3607
=> add package 'balalaika_bear'

README.md
Added ueberauth_foursquare to Auth section
=> Added ueberauth_foursquare to Auth section

README.md
##Title
Adds link to elixir related confreaks video
##Description
Uses the tag filter to list all confreaks.tv videos on elixir. I personally found these videos really helpful when pickup up the language and thought others might too.
=> Add Confreaks link

README.md
##Title
##Description
Resolves "#task-number"
=> Add flowex package to Actors group (#3611)

README.md
##Title
Adds Monkey interpreter to the list of languages
##Description
Hi! I just added my implementation of an interpreter for a js-like language.
It is implemented in Elixir, using only the stdlib and I hope it is of use for someone else. :)
Adds Monkey interpreter to the list of languages
=> Adds Monkey interpreter to the list of languages

README.md
=> Add package "gen_task"

README.md
Resolves https://github.com/h4cc/awesome-elixir/issues/2020
=> Add "topo"

README.md
Resolves https://github.com/h4cc/awesome-elixir/issues/2673
=> add package "explode"

README.md
=> Add Package "cashier"

README.md
Add [jeaux](https://github.com/zbarnes757/jeaux) to validations section
=> Add jeaux to validations section.

README.md, tests/mix.lock
Add Package "rummage_ecto"
Add Package "rummage_phoenix"
Resolves #3858 
Resolves #3881 
Add rummage
=> Add rummage

README.md
Reverts h4cc/awesome-elixir#3481
Going to put it back because I got some time to play with it, to use it in one of my projects, and made a 1.0 release.
=> Revert "remove my own package"

README.md
Add Package "mongodb_ecto"
Resolves #915
=> Added Package mongodb_ecto (#915)

README.md
=> Add Package "Ueberauth_Microsoft"

README.md
Add Package "OK"
Resolves #1110 
Add OK library to both Errors and Macros sections.
* https://github.com/CrowdHailer/OK
=> Add Package "OK"

README.md
Resolves #3240.
Chosen category: 
[Utilities](https://github.com/h4cc/awesome-elixir#utilities), as it is a tool meant to abstract away implementation details of key/value stores as to allow deferring the decision of the optimal one for later.
Other considered categories: 
- [caching](https://github.com/h4cc/awesome-elixir#caching)
Didn't feel like the right fit, as it can be used for more than caching, although its most common use-case would be as a utility to abstract a cache store to experiment with other implementations down the line.
- [datastructures](https://github.com/h4cc/awesome-elixir#algorithms-and-data-structures)
Didn't feel like the right fit, as it only wraps other data structure implementations to expose a key/value store interface.
- …
=> Add Package "mnemonix" – a unified interface to key/value stores

README.md
Nanobox is a platform for creating isolated development environments that are deployable anywhere. While it could potentially fit under multiple categories, it makes the most sense under Deployment
=> Add Nanobox

README.md
Add Package "tabula"
Resolves #1130
Adds `tabula`
=> Add Tabula (closes #1130)

README.md
Add Package double
Resolves #3646 
Add double library to Testing section.
- https://github.com/sonerdy/double
=> Added double library

README.md
Added the [`Ecto.Rut`](https://github.com/sheharyarn/ecto_rut) package to `ORM` section. Resolves #2988.
=> Added Package Ecto.Rut

README.md
=> Add Package "optimus"

README.md
=> Add Package "ivar"

README.md
=> Add package "Geonames".

README.md
Resolves #3832
TaskBunny is a background job processing library developed by [Square Enix](https://en.wikipedia.org/wiki/Square_Enix).
https://medium.com/@ono/introducing-taskbunny-background-jobs-in-elixir-45d090fbba8
=> Add package "task_bunny"

README.md
Add Package "Sippet"
An Elixir library designed to be used as SIP protocol middleware.
Add Sippet
=> Included the Sippet Elixir library

README.md
##Title
Add Package "sigaws"
##Description
Resolves "#4187"
Add sigaws
=> Add Package "sigaws"

README.md
##Title
Add Package "plug_sigaws"
##Description
Resolves "#4189"
Add plug_sigaws
=> added plug_sigaws (#4189)

README.md
=> Add Package react_phoenix

README.md
=> Add package "Clope"

README.md
Mines is a minesweeper clone in the terminal, of which I am the author.
=> Add Package "mines"

README.md
=> Add Package graphitex

README.md
=> Add Package Elastic

README.md
=> Versionary

README.md
=> Add Package firex

.travis.yml, tests/check.exs, tests/mix.exs, tests/mix.lock
Also remove an unsafe variable warning and use latest OTP release on Travis
=> Update dependencies for tests

README.md
Adding [Veritaserum](https://github.com/uesteibar/veritaserum), sentiment analysis based on afinn-165, emojis and some enhancements.
=> Add Package Veritaserum

README.md
=> Add Package meeseeks

README.md
Please add "Startup Job", an umbrella project to search startup jobs scraped from websites, of which I am the author.
Add Startup Job
=> Add Startup Job

README.md
=> Add Package "Rock"

README.md
This commit adds a link and description for Elixircards website.
=> Add Elixircards Reference

README.md
=> Add ethereumex

README.md
Add Package "jalaali"
A Jalaali (Jalali, Persian, Khorshidi, Shamsi) calendar system implemention for Elixir
Add Jalaali
=> Add Jalaali

README.md
Title: "Elixir for Programmers"
Link: https://codestool.coding-gnome.com/courses/elixir-for-programmers
Description: Functional, Parallel, Reliable (and fun!), taught by Dave Thomas
=> Add screencast "Elixir for Programmers"

README.md
Update the description of the fun_with_flags library
Update the description of the `fun_with_flags` library to offer a better summary of the latest features.
Update the description of the fun_with_flags library
=> Update the description of the fun_with_flags library

README.md
Add Package "ExRLP" - Elixir implementation of Ethereum's RLP (Recursive Length Prefix) encoding
=> Add Package ExRLP

README.md
##Title
Add Package "alice"
##Description
Resolves "#1671"
Add Alice bot framework
=> Add package "alice"

README.md
Adding [neuron](https://github.com/uesteibar/neuron), a GraphQL client for Elixir.
=> Add Package Neuron

README.md
Added the [`Que`](https://github.com/sheharyarn/que) package to the `Queue` section. Resolves #3576.
=> Added Package Que

README.md
=> Add Package Petrovich

README.md
##Title
##Description
Resolves "#task-number"
=> Update expat description.

README.md
Add books "Craft GraphQL APIs in Elixir with Absinthe" and "Learn Functional Programming with Elixir"
Add the books "Craft GraphQL APIs in Elixir with Absinthe" and "Learn Functional Programming with Elixir" that are going to be published in 2017.
add two books that will be published in 2017
=> add two books that will be published in 2017

README.md
Add a `Phoenix` screencast tutorial
Add LearnPhoenix.tv!
=> Add a `Phoenix` screencast tutorial

README.md
`download`
Downloads a file from the url easily.
https://github.com/asiniy/download
=> Adding `download` package

README.md
`vultr`
Simple wrapper for the Vultr API
https://github.com/avitex/elixir-vultr
=> Add Package "vultr"

README.md
=> Add Package "bootleg"

README.md
=> Adding ecto_materialized_path package

README.md
Add book "Adopting Elixir"
Add book 'Adopting Elixir' which is going to be published in Nov 2017.
add book 'Adopting Elixir' which is going to be published in Nov 2017
=> Add book "Adopting Elixir" (Nov 2017)

README.md
##Title
Add Package shorter_maps
##Description
Resolves #2266
Add shorter_maps
=> Add shorter_maps

README.md
A toolbar for Phoenix projects to interactively debug code and display useful information about requests: logs, timelines, database queries etc.
https://github.com/kagux/ex_debug_toolbar
=> Add Package "ex_debug_toolbar"

README.md
Simple event bus implementation with topic filtering and built-in event store and event watcher. https://github.com/mustafaturan/event_bus
=> Add Package "event_bus"

README.md
The last major release was a year ago, no commits in 7 months.
=> Remove abandoned project

README.md
Added `crawler` -  A high performance web crawler in Elixir.
=> Added `crawler`

README.md
Add Package "blue_bird"
Link: https://github.com/KittyHeaven/blue_bird
Description:
BlueBird is a library written in the Elixir programming language for the Phoenix framework. It lets you generate API documentation in the API Blueprint format from annotations in controllers and automated tests.
=> Add package BlueBird to topic "Documentation"

README.md
Add Package "phoenix_routes_js"
Phoenix routes helpers in javascript code and browser console.
Now task number yet.
Commit message / hash:
Add phoenix_routes_js / 3dd243964589955eb5b7c3958a9be1765179c952
=> Add phoenix_routes_js

README.md
=> Add Package "plug_password"

README.md
Add Package [exreleasy](https://github.com/miros/exreleasy)
Resolves #3446
=> Add Package exreleasy

README.md
There is no open issue for the lib.
=> Adding triplex to the ORM and datamapping section

README.md
Add chaperon HTTP load testing framework
Chaperon is a load & performance testing tool & framework for HTTP based services (including WebSockets). It allows defining reusable load test scenarios that can be combined into larger scenarios easily. It also provides an API for doing common things with web services, supports running load test scenarios in a cluster (if additional resources are needed) and also tracks common metrics in per-scenario histograms. Metric export options include CSV & JSON and can be extended to custom metric output formats, if needed.
=> Add chaperon HTTP load testing framework

README.md
Added the [`ExPlay`](https://github.com/sheharyarn/explay) package to `Third Party APIs` section. Resolves #3149.
=> Added Package ExPlay

README.md
Added the [`BetterParams`](https://github.com/sheharyarn/better_params) package to `Framework Components` section. (There wasn't an issue about this package for some reason).
=> Added Package BetterParams

README.md
Add Package [basic_auth](https://github.com/CultivateHQ/basic_auth)
Elixir Plug to easily add HTTP basic authentication to an app.
=> Added basic_auth

README.md
Add Package "elixir-on-docker"
##Description
Not on hex as its just a github repository
=> Add the Elixir on docker template project

README.md
Add Package "samly"
Resolves #4332
Add samly
=> added samly lib

README.md
Add Package "ace"
Resolves #3050
HTTP web server and client, supports http1 and http2
=> Add Ace to HTTP section

README.md
Add Package "random_user_api".
Resolves #2489.
Added random_user_api.
=> Add random_user_api

README.md
Add Package "turn_the_page"
Resolves #4350
Fast, simple and lightweight pagination system for your Elixir application.
=> Add turn_the_page

README.md
=> Add Package "mockery"

README.md
Resolves #900
A simple, efficient geocoder/reverse geocoder with a built-in cache.
=> Add Package "geocoder"

README.md
No issue :) Adds unsafe definition generator.
=> Add Package "unsafe"

README.md
A multiplayer ship game built with Elixir, Phoenix Framework and Phaser.
=> Add Package "uai_shot"

README.md
Add Package "[test_selector](https://github.com/DefactoSoftware/test_selector)"
A set of test helpers that make sure you always select the right elements in your Phoenix app.
Add Package "test_selector"
=> Add package test_selector

README.md
Add Package "tunnerl"
Resolves #2011
SOCKS4 and SOCKS5 proxy server
=> Add package “tunnerl”

README.md
Add RemoteRetro to applications category
[RemoteRetro](https://github.com/stride-nyc/remote_retro) - A real-time application for conducting Agile retrospectives at [remoteretro.org](https://remoteretro.org) written in Elixir/Phoenix/React.
Thanks!
=> Add RemoteRetro to applications category

README.md
Add Package "phoenix_client_ssl"
Client SSL Authentication Plugs for Phoenix and other Plug-based apps.
=> Add Package "phoenix_client_ssl"

README.md
Add Package "plug_checkup"
PlugCheckup provides a Plug for adding simple health checks to your app
=> Add PlugCheckup

README.md
=> Add Package "rexbug"

README.md
Add Package "torex"
a library for connecting to Tor network
=> Added Torex

README.md
=> Updated Readme added Gringotts for payments.

README.md
Add Package "remove_emoji"
Emoji text sanitizer in Elixir. It can remove any emoji symbol. 😇
https://github.com/guanting112/elixir_remove_emoji
https://hex.pm/packages/remove_emoji
=> add "remove_emoji" package

README.md
Add Package "ex_prompt"
Helper package to add interactivity to your command line applications as easy as possible.
=> Added ex_prompt to Command-Line packages

README.md
Add Package "akd"
Capistrano like, Configurable and easy to setup Elixir deployment automation package.
Add Akd to awesome-elixir!
=> Add akd to awesome-elixir because it's awesome

README.md
This is a plugin for Vim and Neovim that allows for async execution of `mix format` on the current buffer or opening a new window in diff mode that shows what would change.
=> Add vim-mix-format

README.md
[ntru_elixir](https://github.com/alisinabh/ntru_elixir) is a NIF wrapper for libntru which is a fast implementation of NTRU cryptographic algorithm which is quantum computer resistant.
=> Add Package "ntru_elixir"

README.md
Add ElixirCasts.
New screencast added to the Screencasts category.
ElixirCasts helps people learn Elixir and Phoenix one episode at a time.
=> Adds ElixirCasts

README.md
Add Package "gun" https://github.com/ninenines/gun
Add Package "gun" #1578
add http client to http section (HTTP/1.1, HTTP/2 and Websocket client for Erlang/OTP.)
=> http client (HTTP/1.1, HTTP/2 and Websocket client for Erlang/OTP.)

README.md
Add Package "nanoid"
Elixir port of NanoID, a secure and URL-friendly unique ID generator. I'll add this generates a string randomly designed for secure unique ids.
Added Elixir's NanoID port
=> Added Elixir's NanoID port

README.md
Add Package "giza_sphinxsearch"
Resolves #4392
Client Sphinx Search compatible with Manticore.
=> #4392 add giza_sphinxsearch

README.md
Add Package "simple_stat_ex"
Resolves #4393
Ecto compatible library for simple stat keeping by time period.
=> #4393 add simple_stat_ex

README.md
Add Package "Burnex"
Burner email (temporary address) detector.
=> Add Burnex

README.md
Add package `atomex`
ATOM feed builder with a focus on standards compliance, security and extensibility.
=> Add Atomex

README.md
Add Package "skooma"
Resolves #4402
Skooma is a simple data validation library for elixir. Skooma was developed to be used to describe and validate the incoming and outgoing data structures from a REST API, but it can easily be used throughout a code base. No one likes writing data schemas, so the main focus during development was to develop an API that allowed for quick and simple schema creation.
=> Add skooma

README.md
Add Package "Sockerl"
Resolves issue #4285
Sockerl is an advanced Erlang/Elixir socket framework for TCP protocols and provides fast, useful and easy-to-use API for implementing servers, clients and client connection pools.
=> Resolve issue#4285

README.md
Add Package "ecto_facade"
Resolves #4404 
Ecto library that allows to separate reads and writes in replicated database config.
=> Add info about ecto_facade

README.md
Add Package "scribe"
Resolves #4407
Pretty-print tables of Elixir structs and maps. Inspired by hirb.
=> Add package "scribe"

README.md
Add Package "shopify"
Resolves #3625
This package allows Elixir developers to easily access the Shopify API, featuring resource structs to ensure data integrity, testing support and good old pattern matching.
Came out of a hiatus and finally removed the `work in progress` from the description.
=> Added package shopify

README.md
Add Package `plug_canonical_host`
Resolves #1518
A plug to ensure all requests are served from a single canonical host.
=> Add plug_canonical_host

README.md
Add Package "cocktail"
Resolves #4435
An Elixir date recurrence library based on iCalendar events.
=> Add cocktail - An Elixir date recurrence library based on iCalendar

README.md
Add Package "mockingbird"
Resolves #4232
A set of helpers to test code that involves http requests
=> Add mockingbird

README.md
Add Package "getatrex"
Gettext locales automatic translator with Google Translate
=> added getatrex

README.md
Add Package "tidy_ex"
Elixir binding to the granddaddy of HTML tools http://www.html-tidy.org/
Announcement on the elixirforum:
https://elixirforum.com/t/tidyex-elixir-binding-to-the-granddaddy-of-html-tools/14060
=> Added package "tidy_ex" to section HTML

README.md
Add Package "Nebulex"
Resolves #4306
A fast, flexible and extensible distributed and local caching library for Elixir
=> Add nebulex (#4306)

README.md
Add Package "bitmex"
Resolves #3781 
BitMEX client library for Elixir.
=> Add bitmex (#3781)

README.md
Add Package "mexpanel"
An up to date mixpanel api client.
=> Add new Mixpanel Client

README.md
Add the client for Barrel-db document database
=> Add Package "Barrel_Ex"

README.md
No issue :) Adds consistent hash generation via Jumper.
=> Add package "jumper"

README.md
Add Package "glayu"
Resolves #4292
A static site generator for mid-sized sites.
=> Fixes #4292 Add glayu to Static Page Generation

README.md
Add Package "is" inside Validations
Fast, extensible and easy to use data structure validation for elixir with nested structures support.
Validations: Add is library
=> Validations: Add is library

README.md
Add Package youtrack_logger_backend
A logger backend that will post messages to YouTrack.
https://github.com/unifysell/youtrack_logger_backend
* https://github.com/unifysell/youtrack_logger_backend
* A logger backend that will post messages to YouTrack.
* https://www.jetbrains.com/youtrack/
* YouTrack is an issue tracker made by JetBrains.
=> Add Package youtrack_logger_backend

README.md
Repository does not exist anymore
https://github.com/mustafaturan/oceanex
=> Remove oceanex

README.md
Add Package Rediscl
Resolves #4470 
A minimal Redis client with connection pooling and pipe query builder
=> Added packages rediscl #4470

README.md
Saxy is an XML parser and encoder in Elixir that focuses on speed and standard compliance.
=> Add Package "Saxy"

README.md
=> Add Package "bimap"

README.md
=> add ratekeeper package

README.md
Add Package "speakeasy"
Resolves #4475
Middleware based authentication and authorization for Absinthe GraphQL powered by Bodyguard
=> adding speakeasy

README.md
Add Standalone application "captain_fact"
CaptainFact is a real-time and collaborative fact-checking tool dedicated to videos, implemented as an Elixir umbrella application.
=> Add CaptainFact to standalone applications

README.md
Add Package "ecto_job"
Resolves #4397 
A transactional job queue built with Ecto, PostgreSQL and GenStage.
=> - added package "ecto_job" under *Framework Components*

README.md
Add Package "google-cloud"
Resolves #4399 
Add package to all the client libraries to interact with Google APIs.
=> Add link to google-cloud

README.md
Add Resource "Awesome Elixir and CQRS"
New awesome list added to the "Other Awesome Lists" section.
=> Add Awesome Elixir and CQRS list

README.md
Hey 👋 
I wrote a small Chrome extension about a month ago which replaces the new tab with a random function from the Elixir core lib along with all the documentation and thought it might make a nice addition to this list.
Thanks,
Ville
=> Adding Elixir Tab to Resources.Reading

README.md
##Title
##Description
Resolves "#task-number"
=> add torch project

README.md
##Title
Add Package "taggart"
##Description
Add taggart templating project.
Add "taggart"
=> Add taggart

README.md
Elixir cheat-sheet
Cheat-sheet about GenServer and Supervisor
Add cheat-sheet about GenServer and Supervisor
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h4cc/awesome-elixir/4387)
=> Add cheatsheet resources

README.md
=> Add ex_cli to CLI applications

README.md
https://hackr.io/tutorials/learn-elixir
=> Added Curated List of Elixir Resources

README.md
Add Package "exsms"
A Elixir library for sending transactional SMS - supoprts Sendinblue, mailjet ,msg91 and textlocal
=> Adding `Exsms`

README.md
Added the [`Memento`](https://github.com/sheharyarn/memento) package to the `ORM and Datamapping` section.
=> Added Memento Package

README.md
Removes Blackbook from auth section as it has has been taken down
=> Remove Blackbook

README.md
Add Package "rihanna"
Resolves #4455
Rihanna is a high performance postgres-backed job queue for Elixir
=> Add Rihanna to Queues

README.md
Add Package "mason"
I created a small package which was immensely helpful for us and want to share it with other developers :-)
Mason uses superpowers to coerce maps into structs. This is helpful e.g. when you interface a REST API and want to create a struct from the response.
=> feature: added mason to the list of algos & data structures

README.md
Add Package "RandomStringGenerator"
Generate a random string based on a given string pattern.
=> Add RandomStringGenerator

README.md
Add Package "sshkit"
Resolves #3752
A toolkit for performing tasks on one or more servers, built on top of Erlang’s SSH application
=> Add sshkit

README.md
Add editors ElixirLS and vscode-elixir-ls
Add both package and editor to the list
ElixirLS is the frontend-independent server for Elixir that implements Microsoft's LanguageServer protocol (LSP). VSCode ElixirLS is a frontend extenstion for Visual Studio Code that utilizes the elixir-ls.
=> Add ElixirLS and vscode-elixir-ls to Editor section

README.md
Add Package pay_pal
PayPal REST API client for the Elixir language
=> add paypal package

README.md
=> Removing Anilixir

README.md
=> Removing Apostle

README.md
Link currently does not resolve
=> Removing Elixre

README.md
Link is currently not resolving
=> Removing Elixir Playground

README.md
Add Package `firmata`
Resolves #1402
This package implements the Firmata protocol.
=> Add firmata

README.md
closes #2250
Add Package texas
Resolves #2250
Texas is a powerful abstraction over updating your clients using server-side rendering and server-side Virtual DOM diff/patching.
=> Add Package texas

README.md
Link currently displays a parking site (Domain for sale)
=> Removing Erlang Patterns

README.md
Add Package "rs_twitter"
Alternative for extwitter. It's low level, more simple client and you can get more data using it.
=> Adds rs_twitter - low level twitter client

README.md
Add Package "telemetry"
No issue was found.
Dynamic dispatching library for metrics and instrumentations.
=> Add telemetry

README.md
Add Package "opus"
Resolves #4519
Opus is a framework to build business logic components.
It has similarities to https://dry-rb.org/gems/dry-transaction/ and http://trailblazer.to/gems/operation/2.0/
=> Add opus (#4519)

README.md
Title
Add Package "bonny"
Description
Resolves #4532
Commit message
Kubernetes Operator Development Framework
=> Add bonny (#4532)

README.md
Add Package "scenic"
Resolves #4518
Scenic is a client application library written directly on the Elixir/Erlang/OTP stack. With it you can build applications that operate identically across all supported operating systems, including MacOS, Ubuntu, Nerves/Linux, and more.
Scenic is primarily aimed at fixed screen connected devices (IoT), but can also be used to build portable applications.
=> Add scenic

README.md
Add Package "terminator"
Resolves #4535
Terminator is granular ACL elixir library which allows to define user abilities with relations to _Roles_, _Entities_, _Abilities_. Custom DSL allows to require and protect code only for authorized users.
=> Add terminator

README.md
Fast Expat based Erlang XML parsing library.
=> Add Package "fast_xml"

README.md
Just removes the websites that are down.
Related PRs:
https://github.com/h4cc/awesome-elixir/pull/4511
https://github.com/h4cc/awesome-elixir/pull/4510
https://github.com/h4cc/awesome-elixir/pull/4509
=> Remove sites that went off

README.md
=> Remove dead link to expired domain

README.md
Add TikTak to the list of awesome Elixir resources.
TikTak is a fast and lightweight web scheduler written in Elixir.
Add TikTak to the list of awesome Elixir resources.
=> Add Tiktak (Fast and lightweight web scheduler)

README.md
Add Package "cyanide"
Resolves #4529
An Elixir BSON encoding/decoding library.
=> Add cyanide

README.md
No issue yet, but publish was recent.
=> Added package sleeplocks

README.md
Add Package "git_hooks"
Resolves #4434 
Add git hooks to Elixir projects
=> Add git_hooks

README.md
Add Package "optimal"
Resolves #4443
A schema based keyword list option validator.
=> Add optimal

README.md
Add example "tilex"
source code for the hashrocket TIL site
Today I Learned is an open-source project by the team at Hashrocket that catalogues the sharing & accumulation of knowledge as it happens day-to-day. Posts have a 200-word limit, and posting is open to any Rocketeer as well as select friends of the team. We hope you enjoy learning along with us.
=> Add tilex to examples

README.md
Add example "changelog.com"
No issue number associated.
This is the CMS behind changelog.com. It's an Elixir application built with the Phoenix web framework, PostgreSQL, and many other great open source efforts.
=> Add changelog.com source code to examples

README.md
Add example "hexpm"
No relevant issue number
API server and website for Hex written in Phoenix 1.3
=> Add hex.pm source to examples

README.md
Add Tool Elixir Auto Test
Resolves #4506
Add Tool Elixir Auto Test
=> Add Tool Elixir Auto Test

README.md, tests/check.exs
I've kept the original commit of @paralax and added another one to make the build pass, by removing the duplicated entries.
=> Fix failing build of #4299

README.md
=> Remove Alher entry

README.md
Add Package "Clamxir"
A database wrapper for ClamAV
ClamAV wrapper for elixir based on clamby
=> Add Clamxir on security section.

README.md
Resolves #4573
Validation for Singapore National Registration Identity Card numbers (NRIC)
=> Add package 'ex_nric'

README.md
Add Package "ex_progress"
A library for tracking progress across many tasks and sub-tasks.
=> Add package 'ex_progress'

README.md
=> add elixir bridge to vert.x event bus library

README.md
Nanobox is not written in elixir
=> Remove nanobox

README.md
An Elixir implementation of generic n-ary tree data structure
Add Package "nary_tree"
Resolves #4587
An Elixir implementation of generic n-ary tree data structure
=> Add nary_tree

README.md
Add https://github.com/xou/elixlsx to the "Office" section
=> Add Package "elixlsx"

README.md
`vim_snake` is a small project built by Phoenix framework and Phaser. It's a snake game with Vim-style keybinding, allow multiple players to join and play in a real-time board
=> Add vim_snake

README.md
Add Package "fake_server"
Resolves #2960.
FakeServer is an HTTP server that simulates responses. It can be used in test and development environments, helping to validate the behavior of your application if there are errors or unexpected responses from some external HTTP service.
=> Add fake_server (#2960)

README.md
High-level web scraping framework done with Elixir.
=> Add Package Crawly

README.md
add coderplanets.com to Example section
[coderplanets.com](https://github.com/coderplanets/coderplanets_server) is a IT-related community platform in china, the server is build with phoenix & absinthe.
=> Add coderplanets.com to Example section

README.md
Add Package ["Pow"](https://github.com/danschultzer/pow)
Resolves #4606 
Add Pow an extendable authentication library for Phoenix and Plug-based apps.
=> Add Pow to Authentication libraries

README.md
Add Package "Panoramix"
An open-source client library for sending requests to [Apache Druid](http://druid.io/) from applications written in Elixir.
=> Add Panoramix

README.md
Add screeencast resource "Alchemist Camp"
Resolves #4390 
Alchemist Camp has many hours of free, project-based Elixir-learning screencasts.
=> Add Alchemist Camp to screencasts

README.md
Add Package "Add access pass"
Resolves #4428 
It provides a full user authentication experience for an API. Includes login, logout, register, forgot the password, forgot username, a confirmation email, and all that other good stuff. Includes plug for checking for authenticated users and macro for generating the required routes.
=> Add access pass (#4428)

README.md
Add Package "ExGram"
Resolves #4432 
ExGram is a library to build Telegram Bots, you can use the low-level methods and models, or use the really opinionated framework included.
=> Add ExGram (#4432)

README.md
Add docs to some of the packages suggested.
There are many packages that do not indicate documentation. If is there any issue open regarding this change, please inform me.
This PR is adding docs to some of the packages listed.
=> Add some docs links

README.md
Add Package "conecta-elixir"
Add a link for the Mexican payment API, Conekta.
This packages is basically a wrapper for an API called Conekta, base in Mexico.
=> Add Conekta wrapper library

README.md
Add Package epub_cover_extractor
Add a link for the package epub_cover_extractor
A tools for getting covers from EPUBS
=> Add epub_cover_extractor

README.md
Add Package Medusa
Resolves #4583 
Elixir static site generator that supports Pug.
=> Add Medusa (#4583)

README.md
Add Package "Binbo"
Binbo is a Chess representation written in pure Erlang using Bitboards. It is basically aimed to be used on game servers where people play chess online.
Add Binbo to the Games section
=> Add Binbo to the Games section

README.md
Added Igthorn application
Igthorn is a batteries-included cryptocurrency trading platform written in Elixir. It is a boilerplate for kick-starting your crypto trading project. It contains everything you need to immediately focus on writing profitable algos instead of worrying about setup, custom framework etc.
=> Igthorn Cryptocurrency trading platform added

README.md
https://github.com/sorentwo/oban
Add Package "oban"
=> Add oban to Queue section

README.md
Package have a lot of stars. It's quite popular. Even more popular then prometeus.ex.
=> Add wobserver

README.md
Add Package "tai" to Applications
A composable, real time, market data and trade execution toolkit
https://github.com/fremantle-capital/tai
=> Add tai to applications

README.md
Add Package "flume"
Resolves #4667 
A blazing fast job processing system backed by GenStage & Redis.
=> Add flume package to the Queue section

README.md
Add Package "hades"
Resolves #4675
A wrapper for NMAP written in Elixir.
=> Added hades to network tool list

README.md
=> Add missing newline

README.md
=> Remove .git, be consistent

README.md
Actively developed recaptcha library
* https://github.com/samueljseay/recaptcha
* https://hex.pm/packages/recaptcha
=> Add Package recaptcha

README.md
Hi 👋 
* Add puppeteer_pdf
* Add chromic_pdf
* Mention that pdf_generator also supports puppeteer now
I checked, doesn't resolve any issues.
=> Update section on PDF libraries.

README.md
Add Package "pathex"
Zero-dependency compile-time created functional lenses
=> Added pathex to Macros

README.md
Add Package "workbench"
From Idea to Execution - Manage your trading operation across a globally distributed cluster.
=> Add workbench to applications

README.md
Add packages "broadway" and "surface"
Two popular Elixir libs: broadway by Plataformatec/Dashbit, surface for Phoenix LiveView.
Two popular Elixir libs: broadway by Plataformatec/Dashbit, surface for Phoenix LiveView.
=> Add packages "broadway" and "surface"

README.md
Add Package "emojiclock"
Resolves #4192 
An Elixir module for giving you an emoji clock for a given hour.
=> Add emojiclock to Date and Time

README.md
Add Package "smile"
Resolves #3435
Small lib for converting emoji mappers to emoji characters, like in Slack messages.
=> Add smile to Text and Numbers

README.md
Add Package "Pillar"
No issue
Clickhouse client based on HTTP
=> Clickhouse client

README.md
=> Add/Update recent beginner-focussed Phoenix + LiveView Tutorials 

README.md
Add Package "elixir-xml-to-map"
Add Package "elixir-map-to-xml"
Adds a few useful XML related packages for converting to and from Elixir maps.
Add elixir-xml-to-map and elixir-map-to-xml to XML section.
=> Add XML packages: elixir-xml-to-map, elixir-map-to-xml

README.md
Add Package "definject"
Resolves #4712 
Unobtrusive Dependency Injector for Elixir
=> Add Package "definject"

README.md
Finch: [https://github.com/keathley/finch](https://github.com/keathley/finch)
=> Add finch HTTP client

README.md
Add Package "mox"
Resolves #4717
Mocks and explicit contracts for Elixir
=> Add 'mox' library

README.md
Add Package "Nova Elixir"
Resolves #4721
Syntax highlighting and code completion for Elixir files (.ex, .exs, .eex) in Nova.
=> Add ‘Elixir Nova’ plugin for Nova editor

README.md
Add Package "elasticsearch_elixir_bulk_processor"
Resolves #4719
Adding elasticsearch_elixir_bulk_processor to the search seciton
=> Add Package "elasticsearch_elixir_bulk_processor"

README.md
Add Package "ecto_psql_extras"
Ecto PostgreSQL database performance insights. Locks, index usage, buffer cache hit ratios, vacuum stats and more.
=> Add ecto_psql_extras

README.md
Add Package "uef-lib"
Useful Erlang Functions Library that provides modules for manipulating lists, binaries, maps, numbers, date and time. It can be used in OTP applications and contains some functions optimized for performance in specific cases (e.g. for file I/O operations or binary transformations).
Add uef-lib to the Utilities section
=> Add uef-lib to the Utilities section

README.md
Addresses https://github.com/h4cc/awesome-elixir/issues/4672
=> add information about Linguist status

README.md
Add Package `markdown_test`
Resolves #4649
Test the Elixir code in your markdown files.
=> Add markdown_test

README.md
Add Package "Walkman"
Isolate tests from the real world, inspired by Ruby's VCR.
#4665
=> Add Walkman to the testing category

README.md
Add tool"Csv2sql"
Resolves #4726
Csv2sql is a fast and fully automated tool to import large CSV files to an RDBMS(MySQL or Postgres).
=> Add Csv2sql

README.md
Add Package "Runhyve"
Resolves #4603
Added Runhyve to list
=> Adding runhyve to Artifical Inteligence list

README.md
Add Package "exor_filter"
Resolves #4728
Erlang nif for xor_filter. 'Faster and Smaller Than Bloom and Cuckoo Filters'.
=> Add exor_filter

README.md
Hey @h4cc 
just a typo...
Cheers!
=> Typo: releated -> related

README.md
=> Add package flow

README.md
Add package "ex_changerate"
Elixir client for free exchange and cryptocurrency rates API, no access key required
=> Add ex_changerate

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
At the moment we have 2.7k open issues that should be probably closed,
as the vast majority of them are out of date.
A few people have also been opening issues instead of pull requests, so
I think it's time to do something about it: I've updated the templates
to make it clear that new contributors can simply open a PR.
=> Update GitHub issue and pull request templates

README.md
=> Add Extrace library

README.md
Add Tongue package
Elixir port of Nakatani Shuyo's natural language detector
=> Add Tongue library

README.md
Fix SYNRC libraries
Fix SYNRC libraries: BPE N2O KVS NITRO FORM FS. I've fixed repos and titles for my libs and added a couple.
=> Fix SYNRC libraries: BPE N2O KVS NITRO FORM FS, etc.

README.md
**Title**
Add phx_gen_auth
**Description**
An authentication system generator for Phoenix 1.5 applications.
=> Add phx_gen_auth

README.md
=> Add temple to Templating section

README.md
Add bitcoinex library with high-quality Bitcoin and Lightning Network utilities in Elixir.
=> Add bitcoinex library for Bitcoin utilities

README.md
Adds hush in the configuration section
=> Add hush library

README.md
Add hush_aws_secrets_manager
Add hush_gcp_secret_manager
=> Update hush description & add hush providers

README.md
=> Add SOAP client which is not abandoned

README.md
It's a library for generating random data in the Erlang ecosystem.
https://github.com/mrdimosthenis/minigen
=> Add minigen to the Text and Numbers section

README.md
Synapses is a lightweight library for neural networks
https://mrdimosthenis.github.io/Synapses/?elixir
=> Add Synapses into Artificial Intelligence

README.md
=> Add DepViz to Code Analysis section

README.md
=> Add code_signing to Security

README.md
Added `guardian_db` and `guardian_redis`
=> added `guardian_db` and `guardian_redis`

README.md
Add Elixir client library for the Tradehub blockchain.
=> Add Elixir client library for the Tradehub blockchain

README.md
An Elixir wrapper for GraphicsMagick command line.
=> Add package gi

README.md
=> Added PardallMarkdown (Static Page Generation)

README.md
`excellent_migrations` is a tool that analyses database migrations and detects potentially dangerous operations. 
It's well documented and actively maintained.
It's similar to a popular Ruby gem `strong_migrations`.
=> Add excellent_migrations

README.md
=> Add mix.nvim - Plugin for Neovim

README.md
Owl is a toolkit for writing command-line user interfaces in Elixir.
=> Added Owl into Command Line Applications

README.md
Adds Skogsrå,
it improves the use OS env variables by giving typecasting and documentation, runtime reloading and other features
=> Add Skogsrå Config Library

README.md
Added the Elixir Foundation video series!
=> Added Elixir Foundation screencast series

README.md
added BORSH seriazlizer and NEAR RPC API Elixir library
=> added BORSH seriazlizer and NEAR RPC API Elixir library

README.md
added [enux](https://hex.pm/packages/enux) to configuration section
=> added enux

README.md
added [jsonc](https://hex.pm/packages/jsonc) to json section
=> added jsonc

README.md
=> Add type conversion library

README.md
=> added elasticlunr to Search Section

README.md
thank you for this awesome resource!
=> add conrex package to algorithm section

README.md
Adding a link for Faktory Worker which solves a similar problem to Oban but using Faktory which is Redis backed and polyglot for situations where that may be beneficial.
=> Add faktory_worker to Queue section

README.md
Adding beamchmark to Benchmarking section
=> Adding beamchmark to Benchmarking section

README.md
=> Add Rayex to Games

README.md
Add Package "int_set"
Resolves #4646 
A time- and memory-efficient unordered data structure for positive integers.
=> Added package int_set

README.md
Hey there,
I have added a Free PO file editor, it is a free online tool for translating PO files during Elixir localization.
=> Added Free PO file editor

README.md
I'm the author of [Patch](https://github.com/ihumanable/patch) a new mocking library for Elixir.  I would appreciate your consideration in including it in the awesome-elixir list.
=> Add patch to the Testing Section

README.md
=> Added typed_struct library in section Marcos

README.md
Add game Pictionary.
Pictionary is a picture guessing and drawing multiplayer game(Clone of [skribble](https://skribbl.io/)).
=> Add game Pictionary

README.md
add a youtube playlist with a full elixir course
=> Full course of elixir in spanish languaje

README.md
Add nacha library with tools for generating and parsing NACHA files for US ACH bank transfers.
=> Add nacha library with nacha file processing tools

README.md
Elixirlibs.com
A curated list of Elixir libraries
Basically a curated version of this awesome Elixir list but separated by category and with its own website and search bar. I originally created it for my own use but realized it would be useful for others too. I update it on an ongoing basis.
=> Add Elixirlibs.com

README.md
An implementation of Mars Rover Kata with some additions
=> Added Rovex example

README.md
=> Add ex_jack, ex_alsa, caddishouse.

README.md
=> Added Elixir Succinctly ebook

README.md
Add Package "appsignal-elixir"
The AppSignal for Elixir package collects exceptions and performance data from your Elixir applications and sends it to AppSignal for analysis. Get alerted when an error occurs or an endpoint is responding very slowly.
=> adding error tracking package

README.md
Add Package "graphex"
Resolves #815
A library for composing and executing task graphs in elixir.
=> Add graphex #815

README.md
Add Package "plugmap"
Resolves #4289 
Plugmap is sitemap generation library for Plug/Phoenix Framework
=> Add package plugmap #4289

README.md
Add Package "SRTM"
Resolves #4640
Query locations for elevation data from the NASA Shuttle Radar Topography Mission.
=> Add package SRTM

README.md
Podcasts are a great way for people to learn about programming languages and tools. There are a few of them in the Elixir community that may be worth pointing people towards.
=> Adding collection of Elixir podcasts

README.md
=> not found repository weave fixed

README.md
Add Package "ex_lttb"
Resolves #4528
An Elixir downsampling library that retains the visual characteristics of your data.
=> Add package 'ex_lttb'

README.md
Closure Table,  a simple solution for storing and manipulating complex hierarchies, with support for in-memory and Ecto adapters
=> added a link to Closure Table

README.md
Add Package "quarantine"
Resolves #4602 
Quarantine is a tiny OTP application for feature toggles
=> Add quarantine

README.md
Add Package app_optex
Resolves #4589 
Client for AppOptics API. Send metrics and tags to AppOptics time series service.
=> Add app_optex (#4589)

README.md
Add Package ecto_list
Resolves #4598
Simple ordered model management with Ecto.
=> add ector_list(#4598)

README.md
Add package cubdb
Resolves #4596 
CubDB is an embedded key-value database, written in the Elixir language. It runs locally, it is schema-less, and backed by a single file.
=> Add package cubdb

README.md
A client for thumbor and another for property testing.
Add Package "thumbor_client" and "propcheck"
thumbor_client is a client for [thumbor](http://thumbor.org/) created by Globo.com.
=> Add two more libs

README.md
[Recently announced](https://elixirforum.com/t/matcha-first-class-match-specifications-for-elixir/52182), so I thought I'd share here
=> Add Matcha to awesome macros section

README.md
Add two libraries:
- https://github.com/Bounceapp/elixir-vercel : An Elixir wrapper for Vercel's API
- https://github.com/Bounceapp/ex_passbook : Elixir library to create Apple Wallet (.pkpass) files
=> add vercel and passbook

README.md
=> add NimblePublisher

README.md
=> update Omise client

README.md
This pull request resolves issue #4819
=> Add unreal

README.md
Add [poolex](https://github.com/general-CbIC/poolex) library to **Actors** category.
=> Add poolex library

README.md
=> added link to ThinkingElixir Podcast

README.md
[This library](https://github.com/q60/rational) adds new type of numbers and basic math operations for them. Rationals can interact with integers and floats. The library overrides existing functions, so they can work with rationals too.
=> Add qrational

README.md
[This library](https://github.com/q60/complex) adds new type of numbers and basic math operations for them. Complex numbers can interact with other numbers.
=> Add qcomplex

README.md
=> Add ex_check library to Code Analysis

README.md
=> Add Phoenix Turnstile

README.md
Also fixed the URL for `namor`.
=> Add `phoenix_pages` and `phoenix_svg`

README.md
=> Add `site_encrypt`

README.md
Added to category:  Resources > Reading
=> Elixir Code Smells added

README.md
=> Update README.md - added ex_aws_msk_iam_auth plugin

README.md
=> Update README.md - Noizu Labs - Open AI Wrapper

README.md
=> Add `mneme` to testing section

README.md
=> Catalog of Elixir Refactorings added

README.md
This is my own library that I have been using at work for the past 3 years to validate HTML in controller tests. I think others might find it useful too.
=> Add vnu-elixir to HTML

README.md
Hi!
I'd like to add [ex_pression](https://github.com/balance-platform/ex_pression) - library for evaluating user input expressions.
=> Add ex_pression

README.md
* Update README.md
Adding GenAI, a multi provider completion api wrapper that maps inputs and responses to standardized openai style format.
* Update README.md
=> Noizu patch 1 (#1)

README.md
[StreamData](https://github.com/whatyouhide/stream_data) is a nice tool for data generation and property-based testing. It's recently more popular than propcheck and more actively maintained.
(edit: link)
=> Adds the StreamData library to the list

README.md
[Lynx](https://github.com/clivern/lynx) is a Fast, Secure and Reliable Terraform Backend. It is built in Elixir with Phoenix framework.
It has many features so far:
- **Simplified Setup:** Easy installation and maintenance for hassle-free usage.
- **Team Collaboration:** Manage multiple teams and users seamlessly.
- **User-Friendly Interface:** Enjoy a visually appealing dashboard for intuitive navigation.
- **Project Flexibility:** Support for multiple projects within each team.
- **Environment Management:** Create and manage multiple environments per project.
- **State Versioning:** Keep track of Terraform state versions for better control.
- **Rollback Capability:** Easily revert to previous states for efficient infrastructure management.
- **Terraform Locking Support:** The project …
=> Add Lynx - A Fast, Secure and Reliable Terraform Backend

README.md
[Honeycomb](https://github.com/Hentioe/honeycomb) is a library I recently developed. It has a detailed README.md tutorial and complete tests. Already used in production in my own projects.
=> Add honeycomb

README.md
=> Add Expublish to Release Management

README.md
Suggest to add WeightedRandom library https://github.com/JohnJocoo/weighted_random
=> Add WeightedRandom library

README.md
Add elementtui: a library to create terminal user interfaces.
- https://codeberg.org/edwinvanl/elementtui
- https://hexdocs.pm/elementtui/api-reference.html
For full disclosure: I am the creator of the elementtui library.
=> Add elementtui library

README.md
Adding a new library that I created: `ecto_watch`
[It's README](https://github.com/cheerfulstoic/ecto_watch) has more details
=> Add ecto_watch

README.md
=> added phoenix_storybook to Framework Components

README.md
=> Add tucan and vega_lite

README.md
=> Add `kubereq` to Cloud Infrastructure and Management 

README.md
Summary:
Batteries Inclued is an Elixir project built on `k8s` and
`phoenix_live_view`. The elixir code is https://github.com/batteries-included/batteries-included/tree/master/platform_umbrella
Which is part of the mono-repo: https://github.com/batteries-included/batteries-included
Demo Video of our beta: https://www.youtube.com/watch?v=jCzsFvWf8xE
=> docs: Add Batteries Included

README.md
=> Add harpoon

README.md
=> Add Req to HTTP section

README.md
=> Remove plug_graphql entry
