h4cc/awesome-elixir

- README.md
Dynamo and Weber are no longer maintained so I believe it makes sense to remove them from the list.
It would probably be interesting to move exelli to its own section, probably along side plug, and call it something like web server adapters. I haven't done this change though. :)
> Remove dead web frameworks

- README.md
Countries is a collection of all sorts of useful information for every country in the [ISO 3166](https://de.wikipedia.org/wiki/ISO_3166) standard.
It is based on the data from the ruby gem [Countries](https://github.com/hexorx/countries).
#341
> Add countries

- README.md
Scrivener let's you paginate your Ecto queries. I thought it would be useful to add to the Framework Components section.
> Add scrivener to framework components.

- README.md
Link to the elixir-lang TextMate bundle for elixir syntax highlighting in the `Editors` section.
> Add elixir-lang TextMate bundle

- README.md
Hi @h4cc, here is another PR for you.  This one adds `database_url` to the "ORM and Data Mapping" section.  There were a few non-ORM libraries in there already so I concluded this was probably the right place for it, let me know if you'd like me to move it elsewhere.
Closes #621
> Added database_url to ORM/Data Mapping

- README.md
Add the `getopt` library to Command Line Applications.
Closes #615
> Add getopt package

- README.md
Hello, I built a very simple Instagram API wrapper library that currently only supports "/user_recent_media" on their API endpoint and will be adding the remainder of the API shortly but I also wrote pretty good usage documentation for it (see https://github.com/arthurcolle/exstagram), as well as created an example Phoenix app demonstrating it in the wild: https://exstagram-example.herokuapp.com
I hope some find it useful!
> Add Exstagram, Instagram API library for Elixir

- README.md
While `calendar` was previously the only library with a correct timezone implementation, `timex` does now as well. In order to prevent confusion around this, I requested that lau update his README (which he graciously has already done), and I'm reflecting that change here as well for those shopping around for a date/time library to use.
/cc @lau
> Update description for calendar

- README.md
Hi,
I separated the Alchemist-Server from the Alchemist project so that other Editor Elixir package developers could maybe use it too.
Cheers
Samuel
> add alchemist-server to editor section

- README.md
I found "DEPRECATED: Please use Corsica instead" on plug_cors' README.
> plug_cors is deprecated

- README.md
Removing Elixir for the functional Rubyist from the books section as the link leads to a broken Heroku project and by the indigogo page it seems the book has been canceled. https://www.indiegogo.com/projects/elixir-for-the-functional-rubyist#/
> Removing Elixir for the functional Rubyist

- README.md
Project is fresh for now but will most likely fall behind if not maintained.
Is there a better way to mark this project as not being maintained?
> Marking Hyperledger as no longer maintained

- README.md
Phoenix Generator is no longer being maintained by the owner and most of this libs functionality has been rolled into Phoenix at this point.
**Note from Owner**
DEPRECATED: The functionality of these generators is now mostly built into Phoneix and the rest have not been updated in quite some time!
https://github.com/etufe/phoenix_generator
> Removing Phoenix Generator

- README.md
[mdef](https://github.com/pragdave/mdef) is a macro so belongs under "Macros" not "Miscellaneous".
> Move mdef from Miscellaneous to Macros

- README.md
ExDesk is a library for accessing the Desk.com API
http://dev.desk.com
> Add exdesk to this awesome list

- README.md
This PR adds a link for the [ex_crypto](https://github.com/ntrepid8/ex_crypto) library.  It is an Elixir wrapper for the Erlang `crypto` and `public_key` modules.  Some sensible defaults have been provided to try and make the crypto functions easier to use.
> add ex_crypto

- README.md
Fixing the link to the embedded systems section, not adding/removing any libraries
> Fix embedded-systems link

- README.md
Aruspex is more appropriately classified under the algorithms taxonomy
as it deals with solving *hard* computer science problems. Conversely it
doesn't provide and features specific to text or number manipulation.
> Reclassify aruspex under algorithms and datastructures

- README.md
I've not worked on this in some time, and I don't think it offers anything of value over rolling your own app on top of Plug.
> Remove unmaintained Clint project.

- README.md
This commit includes Guri (https://github.com/elvio/guri) to the Networking list.
> Includes Guri to the Networking list

- README.md
Added the `ExSentry` library to the Logging section.  While I was there, I fixed a broken link for the Honeybadger error logging service.
> Added ExSentry and fixed link for Honeybadger

- README.md
I don't think this is strictly allowed, since it's not actually written in elixir, and is nor hex installable. I would argue it's relevant regardless, as it provides specific functionality in order to make Nifs easy and fast to write and use.
If you don't agree, feel free to decline the pull.
> Add Rustler under NIF category

- README.md
http://phoenixscreencasts.com/ is no longer working.
> Remove link no longer working

- README.md
Expool is a small process pooling library for Elixir to help with concurrency.
Resolves #1389
> Added Expool

- README.md
Hey!
We just announced [Absinthe GraphQL](http://absinthe-graphql.org/), a fully featured GraphQL implementation and would love to include it on this list.
Thanks!
- Ben
> Add Absinthe GraphQL Library

- README.md
A CQRS EventStore using Postgres for persistence, written in Elixir.
> Add `eventstore` library to ORM and Datamapping

- README.md
I no longer work on this lib, it was just a learning exercise and people are probably better off using https://github.com/parroty/oauth2ex
> Removed xoauth2

- README.md
A logger backend for posting errors to Slack.
> slack_logger_backend

- README.md
Sentinel is a phoenix authentication library that extends [guardian](https://github.com/ueberauth/guardian), adding functionality desired in most applications. https://github.com/h4cc/awesome-elixir/issues/1639
> Adds Sentinel - a phoenix authentication library

- README.md
Bamboo has been transferred to the thoughtbot repo. It also updates the description since a lot has changed in the last month.
Thanks again for this awesome resource!
> Update Bamboo to point to the thoughtbot repo

- README.md
Logster is an easily parsable, one-line logger for Phoenix and Plug applications.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h4cc/awesome-elixir/1922)
> Added Logster to Logging

- README.md
Superfast, pipelined, resilient Redis driver for Elixir.
Github: https://github.com/whatyouhide/redix
Hex: https://hex.pm/packages/redix
Doc: https://hexdocs.pm/redix/Redix.html
Travis: https://travis-ci.org/whatyouhide/redix
> Add Redix to ORM and Datamapping

- README.md
`ukutaht/elixir-koans` and `elixirkoans/elixir-koans` are the same thing, we just recently moved it from my personal account to an organisation.
> Remove duplicate koans

- README.md
An interactive dependency plotter for your Hex Package
Refer https://github.com/sivsushruth/mixgraph
> [skip ci] Add Mixgraph under miscellaneous

- README.md
The [nerves project](http://nerves-project.org/) is a young but very interesting framework/toolset for building firmware that targets platforms like Raspberry Pi.
It was featured at ElixirConfEU 2016 ([link to video](https://www.youtube.com/watch?v=118-g0ODfgg))
> Add nerves to hardware section

- README.md
Adds the package "ueberauth_auth0" and fixes a typo.
> Add Package "ueberauth_auth0"

- README.md
I was separating this:https://github.com/h4cc/awesome-elixir/pull/2302
- exkanji - A Elixir library for translating between hiragana, katakana, romaji and kanji. It uses Mecab.
Thanks.
> added exkanji

- README.md
Since there is no procedure for this in the ISSUE_TEMPLATE I will try my best:
I'd like to see a "Newsletters" category separated from "Websites", since there are many websites, but not so many newsletters.
But take this suggestion with a grain of salt, as the reason for me creating this category is the fact that I am adding [ElixirWeekly](https://elixirweekly.net) to it :wink:
> Create category "Newsletters"

- README.md
ex_gecko is an elixir client that communicates with Geckoboard API. It supports new dataset API and push to widgets API.
> Add Package ex_gecko

- README.md
No resolves an open issue (just a new library).
Add ex_image_info (image parsing library).
I add [ex_image_info](https://github.com/rNoz/ex_image_info) over the next library that starts with "ex.*" because I saw the same behaviour in previously added packages in awesome-elixir (other that starts with `ex_`).
> Add Package "ex_image_info"

- README.md
Added [ecto_autoslug_field](https://github.com/sobolevn/ecto_autoslug_field)
Automatically creates slugs for your Ecto models.
> Added "ecto_autoslug_field" to Misc section

- README.md
Added 'sizeable' library to Files & Directories. It's on hex.pm, has 100% test coverage with 28 unit tests. Also, we use it in production ;) It's pretty much a no-nonsense port of `filesize.js` from the node ecosystem. 
It's located at [arvidkahl/sizeable](https://github.com/arvidkahl/sizeable).
> Added 'sizeable' library to Files & Directories

- README.md
Sorry for not following the PR format.
In this case I'm not adding a new package but changing the place of one.
`Simple bayes` implements one of the simplest machine learning techniques.
It was classify as "algorithm", sure it is an algorithm but as we have an `Artificial intelligence` section, it should go there.
> move simple bayes from algorithms to artificial intelligence

- README.md
Resolves #2979
Smoothie inline styles of your email templates, and generates a plain text version from the HTML. We extracted this from the codebase at our startup and use it in production. We build this because we couldn't find any library in the ecosystem that provides inlining.
> Add Package "smoothie"

- README.md
Resolves #2972
I just published the authorize library that we use in production at our startup. We need some pretty advanced authorization rules, and there was nothing available as a package that could facilitate this. This is the extraction of the code we use, and it really helped us to implement quite sophisticated authorization rules using very readable code.
> Add Package Authorize

- README.md
[prometheus-plugs](https://github.com/deadtrickster/prometheus-plugs) - Plugs instrumenters/exporter for prometheus_ex.
closes #2103
> Add prometheus-plugs

- README.md
Updating the link to the witchcraft lib so that no longer redirects.
> Update link to witchcraft lib

- README.md
Link currently redirects.  Updating link to point at current repo location.
> Updating link to rebar3_auto

- README.md
getpocket.com currently is missing the transport making github interpret it as an reletive link.
> Fixing included getpocket.com link

- README.md
Link currently redirects. Updating link to point at current repo location.
> Updating link to exrm_heroku

- README.md
Elixirfm is an API wrapper for the Last.fm API
> ADDS Elixirfm to 'Third Party APIs' Category

- README.md
It has moved to its own GitHub organization https://github.com/hedwig-im/hedwig
> Update hewdig's link

- README.md
I also put [elixir.libhunt.com](https://elixir.libhunt.com/) at the bottom to the other curated lists.
> Remove toolbox.elixir.pm since it is no longer maintained

- README.md
Add Package Loki
Loki is a toolkit for building powerful interactive in "phoenix CLI style"  command-line interfaces.
Resolves "#3375"
Add command line application loki
> Add command line application loki

- README.md
This removes the Nest API project from the list:
https://github.com/adamzaninovich/nest
The project is a skeleton project with no functioning Nest code and has not been updated in 2 years.
##Title
Remove Package "nest"
Remove Package "nest"
> Remove Nest API reference

- README.md
Some time ago author has marked that relisa is deprecated, see: https://github.com/SenecaSystems/relisa
> Removed relisa: the author marked it as deprecated

- README.md
[Exgen](https://github.com/rwdaigle/exgen) is a templating library for generating reusable Elixir projects.
> Add "exgen"

- README.md
Moves my `PlugRest` library from "Framework Components" to "REST and API", which is a more precise  category.
> Re-categorize plug_rest as "REST and API"

- README.md
This package was added over 2 years ago in https://github.com/h4cc/awesome-elixir/commit/9b4c524d0f6ca0c2c521ede31ab2522aa7a7f773. Since it still lacks a proper readme and doesn’t look actively maintained, I suggest removing it from this list for the time being.
> Remove package `httprot`

- README.md
This adds [timber](https://github.com/timberio/timber-elixir), a structured logging solution that we've been working on for the past year.
It also removes an old library of ours that is no longer available.
> Add timber - structured logging library

- README.md
I've added a new "Feature Flags and Toggles" section to the list.
These two packages have been added:
* `flippant`
* `fun_with_flags` (disclaimer: I'm the author)
Also, the `molasses` library was already present in the "Miscellaneous" section and I've just moved it.
The packages are listed in alphabetic order.
I could find a couple of other libraries serving the same purpose in hex.pm, but I've only included the ones that have proper test coverage and that seem to be maintained.
This PR would solve issues https://github.com/h4cc/awesome-elixir/issues/3780 and https://github.com/h4cc/awesome-elixir/issues/2614.
> Added a category for feature toggle libraries

- README.md
Add Package "ravenx"
hex: https://hex.pm/packages/ravenx 
github: https://github.com/acutario/ravenx
"Notification dispatch library for Elixir applications". It is extensible notification system for elixir which support email and slack out of the box.
> Add package ravenx

- README.md
Add package "blogit"
Blogit is an OTP application for generating blogs from git repositories containing markdown files.
Resolves #3768
Add package "blogit"
> Add package "blogit"

- README.md
Adding the new Hex Package [ExGtin](https://github.com/kickinespresso/ex_gtin) to the validation section
##Title
Add Package ExGtin to Validation Section
##Description
Add Package "ex_gtin" to the Validations Section of the Library
This Library does GTIN code validation. 
GitHub Link: [ExGtin](https://github.com/kickinespresso/ex_gtin) 
HexDocs Link: [ex_gtin](https://www.hex.pm/packages/ex_gtin)
There is no issue number current open. 
Add ex_gtin library
> Add Package ExGtin to Validation Section

- README.md
Gigalixir is a fully-featured PaaS designed for Elixir that supports clustering, hot upgrades, and remote console/observer.
> Add Gigalixir

- README.md
##Title
Change Package "ex_gtin" name to match standard format
##Description
Changing `ExGtin` to `ex_gtin` in README.md
> Change Package "ex_gtin" name to match standard format

- README.md
Added `opq` - A simple, in-memory queue with worker pooling and rate limiting in Elixir.
> Added `opq`

- README.md
Remove `ecto_hstore` because it is deprecated because ecto provides the functionality directly.
> Remove ecto_hstore

- README.md
Hey there! Thanks for all the hard work y'all put in on maintaining the Awesome Elixir list. It's a big asset to the community.
This pull request adds two OAuth related packages:
* Add Package [oauth2_facebook](https://github.com/chrislaskey/oauth2_facebook) - A Facebook OAuth2 Provider for Elixir
* Add Package [oauth2_github](https://github.com/chrislaskey/oauth2_github) - A GitHub OAuth2 Provider for Elixir
Both packages have spec coverage, documentation, and are available through Hex.
Add oauth2_facebook and oauth2_github
> Add OAuth2 Projects

- README.md
We use this library in our messaging app to normalize phone numbers before they get stored in the database. As well as to verify that a phone number is really a valid phone number before we send a message.
> Add Package "ex_phone_number"

- README.md
Add Package "conduit"
Resolves #3348
Conduit is a framework for working with message queues, with adapters for SQS and AMQP, and plugs for reusable messaging patterns.
> Add conduit

- README.md
Add Package RealWorld.io Elixir + Phoenix example app
Resolves #4365
This is the elixir/phoenix backend implementation of RealWorld.io backend,
which is a clone of Medium.com
> Adding RealWorld.io Elixir + Phoenix example app

- README.md
Move the packages "calliope" and "slime" to the [Templating](https://github.com/h4cc/awesome-elixir#templating) section.
It is the most specific section for them. They were added before the section existed.
> Move Calliope, Slime to Templating section

- README.md
Add Package `licensir`
Add a package called `licensir` that lists the license(s) of all installed packages in your project via a mix task.
> Add licensir package

- README.md
[The Beam Book](https://happi.github.io/theBeamBook/) is probably the most up-to-date and detailed documentation of the Erlang VM, so it seems like a natural fit for the list.
[codec-beam](https://github.com/hkgumbs/codec-beam) is my project, and certainly less impressive. As far as I can tell though, it's the only library to target the Erlang VM without going through the Erlang toolchain.
Please let me know if either of these do not meet the criteria :)
> Add The Beam Book and codec-beam

- README.md
Add Package "machinery"
Resolves #4369
A state machine library for structs in general, it integrates with Pheonix out of the box.
> Adding Machinery to the list

- README.md
Add Package "modest_ex"
**Link:** https://github.com/f34nk/modest_ex
**Description:**
A library to do pipeable transformations on html strings with CSS selectors, e.g. find(), prepend(), append(), replace() etc.
Announcement on the elixirforum: 
https://elixirforum.com/t/modestex-library-to-do-pipeable-transformations-on-html-strings-with-css-selectors/12793
See this issue:
https://github.com/h4cc/awesome-elixir/issues/4415
> Add package 'modest_ex'

- README.md
Add Section "HTML"
Please add a section "HTML" explicitly for html tools and libraries.
See discussion on the forum: 
https://elixirforum.com/t/overview-of-available-html-tools-in-elixir/12905/3
HTML and XML are completely different languages and should not be represented under the same section. Right now all xml and html related packages are subsumed under the section 'XML'. I think this is misleading.
See this issue: https://github.com/h4cc/awesome-elixir/issues/4419
> Add Section "HTML"

- README.md
Add Package [gen_rmq](https://hexdocs.pm/gen_rmq)
GenRMQ is a set of [behaviours](https://hexdocs.pm/elixir/behaviours.html) meant to be used to create RabbitMQ consumers and publishers.
Internally it is using [AMQP](https://github.com/pma/amqp) elixir RabbitMQ client. The idea is to reduce boilerplate consumer / publisher
code, which usually includes:
* creating connection / channel and keeping it in a state
* creating and binding queue
* handling re-connections / consumer cancellations
> Add gen_rmq

- README.md
Add social feed to current applications.
[Feedx](https://github.com/erneestoc/feedx)
OTP umbrella app with a `bus` app for consuming external events and create a feed via `AMQP`, `store` to store and cache feed data, and `web` is a phoenix api for serving the feed.
> Feedx - Add social feed to current applications.

- README.md
A blazing fast matrix library for Elixir/Erlang with C implementation using CBLAS.
(No github issue mentioning matrex package was found)
> Add Package "matrex"

- README.md
Resolves #3509
HipChat client library for Elixir, based on httpc.
> Add hipchat_elixir (#3509)

- README.md
Add Package "quiet_logger"
Resolves #4462
A simple plug to suppress health check logging. Useful when running apps in Kubernetes.
> Add quiet_logger

- README.md
Add Package "gettext"
Resolves #984 
Gettext is an internationalization (i18n) and localization (l10n) system commonly used for writing multilingual programs. Gettext is a standard for i18n in different communities, meaning there is a great set of tooling for developers and translators. This project is an implementation of the Gettext system in Elixir.
> Gettext deserves to be here!

- README.md
`Bunyan: An Elixir Logger` - a distributed `Logger` backend with a lot of thrills by Dave "Pragmatic" Thomas.
Add Package "Bunyan: An Elixir Logger".
Adding `Bunyan: An Elixir Logger` - a **distributed** `Logger` backend with **a lot** of thrills by (none other than) **Dave "Pragmatic" Thomas**.
> Add `Bunyan: An Elixir Logger`

- README.md
Add Package "spandex"
Spandex is a handy distributed tracing library that we use in production at https://github.com/teacherspayteachers
A platform agnostic tracing library
> add the spandex library for distributed tracing

- README.md
Resolves #4482
These packages implement the basic W3C standards for the RDF graph data model and SPARQL graph query language and protocol. They bring the [Semantic Web](https://en.wikipedia.org/wiki/Semantic_Web) and [Linked Data](https://en.wikipedia.org/wiki/Linked_data) ecosystem to Elixir.
> Add RDF.ex and accompanying packages

- README.md
Adds more tools to operate with Cassandra DB in Elixir.
Prior to this change we had only vintikzzz/cassandra_ecto library included in the list.
Unfortunately, this library is not maintainable right now and should be removed.
We have another production-ready solutions to operate with Cassanda DB in Elixir that should be included in this list.
Resolves #3327, resolves #3688
Adds `ecto-cassandra`, `triton`, `xandra` packages, removes `cassandra_ecto` package
> Add more tools to operate with Cassandra DB in Elixir

- README.md
Add Package "ex_cldr" to replace "cldr"
Resolves #2900.
Replaces the cldr library, which has received no update since 2014, with ex_cldr.
> Add ex_cldr

- README.md
Remove Package `raven`
Resolves #4465
The repo now redirects to getsentry/sentry-elixir, so.
> Remove raven as the repo now redirects to getsentry/sentry-elixir

- README.md
A dyndns server written in elixir using the following components:
* phoenix as webfrontend based on elixir/erlang (MIT License)
* PostgreSQL as database backend (PostgreSQL License)
* PowerDNS as DNS server (GNU General Public License v2.0)
* PowerDNS dnsdist as DNS load balancer (GNU General Public License v2.0)
* dehydrated as let’s encrypt client (MIT License)
* nginx as http load balancer (Simplified BSD License)
> Added Networking -> FlyingDdns

- README.md
Add Package "correios_cep"
https://github.com/prodis/correios-cep-elixir
Find Brazilian addresses by zip code, directly from Correios database. No HTML parsers.
> Add correios_cep.

- README.md
Add Package "format_parser"
Resolves #4516
FormatParser can be used to figure out the type and the format of a file. It also can extract some additional information.
> Add format_parser

- README.md
Bake hasn't been maintained for years. Nerves can compile locally in a Docker container so the functionality that it provided isn't needed anymore.
> Remove bake/bakeware

- README.md
Add Package "jsonstream_encoder"
Resolves #4345 
JsonStreamEncoder is a streaming encoder for streaming JSON to an IOish thing in Elixir.
> Add json_stream_encoder

- README.md
Add Package "ratatouille"
No issue number associated
Ratatouille is a declarative terminal UI kit for Elixir for building rich text-based terminal applications similar to how you write HTML.
It builds on top of the termbox API (using the Elixir bindings from ex_termbox].
> Add ratatouille

- README.md
I would just like to move shortuuid from `Cryptography` to `Text and Numbers` as it is a tool to encode UUIDs and all encoding and UUID libs are under that category.
Also changed the name from `ex_shortuuid` to `shortuuid`, the actual package name.
Cheers
> Move shortuuid to Text and Numbers

- README.md
Add Package "AtomVM"
Resolves #4530
AtomVM allows to run Elixir/Erlang code on embedded devices such as ESP32 and STM32 microcontrollers.
> Add AtomVM

- README.md
Add Package "ecto_shortuuid"
Ecto type which adds support for [ShortUUIDs](https://github.com/gpedic/ex_shortuuid).
ecto_shortuuid builds on shortuuid added in #4548 by making it simple to use shortuuid as field types
> Add ecto_shortuuid

- README.md
Change Link to Package, "AWS Clients for Elixir"
No formal issue
Previously linked to project with readme that said, "This project has moved to https://github.com/aws-beam/aws-elixir"
> link updated to reflect moved project.

- README.md
Add the Package "phoenix_meta_tags" from hex.pm
Link: https://hex.pm/packages/phoenix_meta_tags
Description:
A Phoenix library helps to generate meta tags for website.
Resolves #4579
> Add the Package "phoenix_meta_tags"

- README.md
Found a few typos in exsms package description.
> Fix typos in exsms description

- README.md
No addition, just updating an entry. I've changed my username from `Zeeker` to `sascha-wolf` 🙂
> Rename `Zeeker` to `sascha-wolf` after username change

- README.md
Add Package [crudry](https://github.com/gabrielpra1/crudry)
Crudry is an elixir library for DRYing CRUD of Phoenix Contexts and Absinthe Resolvers.
It also provides a simple middleware for translating changeset errors into readable messages.
Crudry is an elixir library for DRYing CRUD of Phoenix Contexts and Absinthe Resolvers.
> Add crudry

- README.md
Updated Quantum dependency repository URL.  
Previous repo was archived and move to the organisation.
> Updated Quantum repository URL

- README.md
Add Package Jisho-Elixir
Resolves #4318 
An API wrapper for Jisho.org, an online Japanese dictionary. Allows users to search by word, symbol, and or tags (refer to docs).
> Add Jisho-Elixir (#4318)

- README.md
Add Package AlloyCI
Resolves #4625 
lloyCI is a Continuous Integration, Deployment, and Delivery coordinator, written in Elixir, that takes advantage of the GitLab CI Runner, and its capabilities as executor, to prepare and run your pipelines.
> Add package AlloyCI

- README.md
Add `elixir_auth_google` package to Authentication section
Resolves #4656
The simplest Google OAuth lib for Elixir.
The fewest number of steps for adding "_Sign in with Google_" to your Elixir/Phoenix App. 
Thanks! ☀️
> Add elixir_auth_google package to Authentication section

- README.md
Add https://github.com/dwyl/phoenix-chat-example to list of Examples. 
Resolves #4658
`phoenix-chat-example` is a step-by-step tutorial/example showing people how to build a Chat App in **Phoenix 1.4** from scratch including testing and deployment. :shipit:
> Add link to phoenix-chat-example to Examples

- README.md
Fix links for Programming Elixir, Programming Phoenix and Études for Elixir
Change links for books:
- Programming Elixir
- Programming Phoenix
- Études for Elixir
> Fix links for Programming Elixir, Programming Phoenix and Études for Elixir

- README.md
Arc is deprecated in favor of waffle and is no longer maintained after 0.11 release.
> Replaced arc with waffle for file uploads.

- README.md
Add Package "telegex"
Resolves #4701
This is a library for building bot applications on the Telegram platform, and the main maintainer is myself.
[Some introductions to it on the official forum](https://elixirforum.com/t/telegex-telegram-bot-library-full-support-for-the-latest-api-versions).
Package link: https://hex.pm/packages/telegex
> Add telegex

- README.md
Add Package "xcribe"
Xcribe is a doc generator for Rest APIs built with Phoenix. The documentation is generated by the tests.
Currently API Blueprint and Swagger (OpenAPI Spec 3.0) specifications are supported.
> Add Xcribe into Documentation section

- README.md
Add Package "geohash_nif"
Resolves #4708
Drop in replacement for Geohash encode/decode library implemented as a NIF with improved performance
> Add geohash_nif to Geolocation libraries

- README.md
WhereTZ is elixir version of Ruby gem for lookup of timezone by georgraphic coordinates.
> Add wheretz

- README.md
Add Package "expyplot"
Adding new package
Expyplot allows you to use 'all' of the functions in matplotlib.pyplot (in reality, there are some that I left out because they don't make any sense in this context, or are deprecated).
> Adding expyplot for using matplotlib.pyplot

- README.md
AskimetEx is a package for use TypePad's AntiSpam services or Askimet endpoints in elixir projects.
Hex url: https://hex.pm/packages/askimet_ex
Documentation: https://hexdocs.pm/askimet_ex/readme.html
> Add package "askimet_ex"

- README.md
Add `phoenix-ecto-encryption-example` to list of Examples 
Resolves #4660
https://github.com/dwyl/phoenix-ecto-encryption-example
Is a step-by-step example/tutorial showing people how to use Ecto Types to seamlessly encrypt/decrypt data stored by Phoenix for at-rest security/privacy. No prior crypto knowledge/experience assumed/required. :shipit:
> Add phoenix-ecto-encryption-example to list of Examples

- README.md
Add Package "Calixir"
Resolves #4706 
Calixir is a port of the Lisp calendar software calendrica-4.0 to Elixir.
Package link: https://hex.pm/packages/calixir
> Add Calixir

- README.md
Add Package "mongodb_driver"
Resolves #4731 
An alternative MongoDB driver for Elixir.
Support for recent versions of MongoDB (4.4) and seems to have the most comprehensive feature set of all available mongodb drivers for Elixir.
> Added mongodb_driver to "ORM and Datamapping"

- README.md
This commit adds WebAssembly as a new category of things. It proposes two entries: `lumen` and `wasmex`. I am currently not aware of more WASM related projects (which are still maintained).
Disclaimer: I'm the author of wasmex
> Added a WebAssembly category

- README.md
mix_test_interactive is based on mix_test_watch, but adds an interactive mode for dynamically changing which tests should be run.
> Add mix_test_interactive

- README.md
Add link to ConfigCat's Elixir SDK. ConfigCat is a hosted feature flag service.
> Add ConfigCat Elixir SDK

- README.md
An author of #4672 updates status of linguist package as abandoned because of lacking of recent commits and failing tests.
But since the May 2020 repo was adopted by @change, and they added significant improvements into the projects - now tests are not failing, CI process uses latest Elixir and OTP versions to run tests, and there were a lot of useful changes.
So let's remove an abandoned status of the repo and also update project URL.
> Linguist package is in active development

- README.md
This PR aims to change Kafka recommended libraries once the current Kafka lib [kafka_ex](https://github.com/kafkaex/kafka_ex) does not provides basic authentication mechanisms to connect to Kafka like SASL. Most of Kafka clusters have this type of authentication and developers can fall in the mistake of start their development with a library that does not accounts such a basic feature.
Based on that I would like to suggest the replace it by [kaffe](https://github.com/spreedly/kaffe).
> Update kafka libraries

- README.md
Ashes has not seen any updates since 2015 and doesn't exist on GitHub anymore.
> Remove abandoned "ashes" package

- README.md
Matcha is a library that helps alchemists work with OTP's [match specifications](https://www.erlang.org/doc/apps/erts/match_spec.html) in a much more intuitive fashion.
Library is well-documented, well-tested, and in active development by myself, preparing for a new release soon.
> Add Matcha library to OTP libraries.

- README.md
Hey there! Thanks a lot for this list!
I'm not sure whether this contribution fits the project ideology 100% or not. `m2cgen` is **not written** in Elixir but **generates** Elixir code. It is a lightweight library with command line interface which allows to transpile trained machine learning models into a native code of Elixir programming language. Examples of generated Elixir code can be found [here](https://github.com/BayesWitnesses/m2cgen/tree/master/generated_code_examples/elixir).
Thanks a lot for your time and consideration!
> Add m2cgen for transpiling ML models into Elixir code

- README.md
`one_time_pass_ecto` is no longer maintained, as described in its current readme file. The author recommends `pot` (already included in this list) or `nimble_totp` from dashbit, which has not yet been included in this list.
> Replace `one_time_pass_ecto` (retired) with `nimble_totp`

- README.md
Firezone is a web UI to manage WireGuard tunnels.
> Add Firezone to the network section

- README.md
Good afternoon, colleagues!
I continue my work on Flow-based programming with Elixir. 
The new library is ALF, and it's a successor of Flowex. Flowex is not supported anymore.
> Replace Flowex with ALF

- README.md
The [Eh](https://github.com/Frost/eh) build is failing and the library has not been maintained since 2015.
> Remove Eh debugging library

- README.md
A technical indicator library for Elixir with no dependencies.
We see crypto trading bot projects both open/closed source [being developed](https://www.elixircryptobot.com) with Elixir as the language is a great fit every other day. This library aims to improve trading decisions by integrating technical indicators into those systems.
In addition to crypto, stock market data, the indicators covered in the [indicado library](https://github.com/thisiscetin/indicado) can be used in many numerical data sets.
I would be very happy if you include my library to your list, thank you.
> Add package indicado

- README.md
**sise** is a simple to use SSDP client (Simple Service Discovery Protocol; which is the "service discovery" part of UPnP)
The implementation is compatible with the UPnP 2.0 spec. Users of the application can either manually `get(...)` the found services and devices or `subscribe(...)` to be notified.
**Documentation:** https://hexdocs.pm/sise/Sise.html
**Hex:** https://hex.pm/packages/sise
**Github:** https://github.com/aytchell/sise
> Added sise into Networking

- README.md
This commit adds Classpert to the "Websites" section, containing around 20 Elixir Online Courses.
> Add Classpert Elixir Online Courses

- README.md
Add Package "dummy"
Resolves #4581 
Elixir mocking that makes sense. Dummy relies on meck and exposes a simple way to mock methods, thanks to a couple of assumptions
> Add Dummy (#4581)

- README.md
Add Package "meseeks"
Remove Package "exquery"
Per the readme of exquery, it should be replaced with meseeks:
https://github.com/rozap/exquery/blob/master/README.md
meseeks is a library for parsing and extracting data from HTML and XML with CSS or XPath selectors.
> exquery is deprecated in favor of meseeks

- README.md
A library for Elixir run-time system code line-level coverage analysis which can use it to evaluate the intergration tests code coverage.
> Add ex_integration_coveralls

- README.md
Hey @h4cc,
Thanks for this awesome resource! I'm one of the open-source contributors to the Flowbite UI library and we have recently built an integration guide for [Phoenix Framework (Elixir)](https://flowbite.com/docs/getting-started/phoenix/) and it works quite well! Luckily, the underlying CSS framework is also Tailwind CSS which means it's nicely in line with the latest 1.7 version of Phoenix.
I though it would be nice to also have a UI library in this list that is compatible or at least has an extensive integration guide. Hopefully I have adhered to all contribution guidelines and I believe it's better to link to the integration guide directly rather than the full package because it's a bit more general-use.
Cheers,
Zoltan
> Add Flowbite library with Phoenix/Elixir integration guide

- README.md
Adds [mahaul](https://github.com/emadalam/mahaul), a one of a kind library to access environment variables in Elixir.
Resolves #4832
> Add mahaul library

- README.md
Adds :
- [ecto_anon](https://github.com/WTTJ/ecto_anon): an ecto library to easily anonymize your data.
- [algoliax](https://github.com/WTTJ/algoliax) - An Algolia library for Elixir, usable with Ecto schemas.
- [chargebeex](https://github.com/WTTJ/chargebeex) - An Elixir client for Chargebee API.
> add: ecto_anon / algoliax / chargebeex

- README.md
Add the `sneeze` package (https://github.com/JuneKelly/sneeze) under the templating section
> Add `sneeze` to Templating section

- README.md
Adding in elixir_error_message which has been in use across several companies like Blitz.gg, Cheddarflow and Requis. Helps to make errors more predictable and renderable
> Add elixir_error_message into Errors section

- README.md
Adds a tutorial from ECSx Hexdocs page, it's a new Entity-Component-System framework made by an engineer from Dockyard. They also wrote a blog post explaining the concept of Entity-Component-System.
> Add ECSx official tutorial under 'Game' section

- README.md
> Add pluggable - A library to build plug-like pipelines

- README.md
This PR fixes the link to the WebAssembly category in order to enable navigation to the correct section in the README.
> Fix link to WebAssembly category

- README.md
I've noticed this issue open https://github.com/h4cc/awesome-elixir/issues/4325 
I thought it might make sense to do PRs by category. If it's ok, I'll proceed with the other categories.
So far, I've been
* eliminating repos with a clear End of Life note in the README by the author or archived.
* removing repos whose last commit was before 2020.
I've been using as a reference both https://awsm-elixir.rubybox.dev/ and the README.
> Abandoned actors packages cleanup

- README.md
Elixir 1.6 version introduced new concept of cheatsheets in exdocs. As a first cheatsheet they implemented it for Enum and this PR puts a proper link in a README file.
> Add Enum cheatsheets

- README.md
Update [Newsletters](https://github.com/h4cc/awesome-elixir/tree/master#newsletters) section to add [Elixir Merge](https://elixirmerge.com/) newsletter.
Elixir Merge is a newsletter that delivers the best of the Elixir community in just two curated updates, featuring news, tutorials, videos, podcasts, and blog posts. Perfect for busy developers who want to know what matters without the overwhelm.
References:
- [https://elixirmerge.com/](https://elixirmerge.com/)
- [Elixir Forum | We started a daily Elixir Newsletter - Elixir Merge](https://elixirforum.com/t/we-started-a-daily-elixir-newsletter-elixir-merge/58525?u=akshayrathod)
> Add Elixir Merge under newsletters

- README.md
[ex_azure_speech](https://github.com/ex-azure/ex_azure_speech) is an Elixir Implementation for the Azure Speech Services SDK.
> Adding ex_azure_speech library

- README.md
Add `UniqueNamesGenerator` in correct order (tests failed previously).
> Add UniqueNamesGenerator to Text and Numbers [PASS]

- README.md
Hye folks! Thank you for maintaining this awesome list of libraries.
I'm proposing a new section for Data Visualization and adding `plox` library.
> Add data visualization section and plox library

- README.md
Introducing [TypedStructor](https://github.com/elixir-typed-structor/typed_structor), a new library for defining types that enhances extensibility and offers detailed [guides](https://hexdocs.pm/typed_structor/introduction.html).
> Add typed_structor

- README.md
This PR adds PubSubx to the Awesome Elixir list.
PubSubx is a publish-subscribe system built on Elixir's GenServer and Registry. For more details, visit https://github.com/sonic182/pub_subx.
No external dependencies for a basic pubsub :smile:
> PubSubx project

- README.md
This adds the `prompt` library to the list of command line applications
> Add prompt to the cli section

- README.md
Add a small utility library that contains `to_atom_in` macro that converts String to atom only if resulting atom is in set of atoms provided.
Useful for validations of request parameters.
> Add to_atom_in to Validations

- README.md
I manually went through the list of archived repositories and selected the ones that can definitely be deleted.
I will attach my notes with a brief explanation of each repository just in case.
Archived repositories that are not marked `:remove:` can still be of some use in my opinion.
```
https://github.com/gmcabrita/bloomex
https://github.com/gmcabrita/cuckoo
https://github.com/gmcabrita/murmur
https://github.com/doomspork/hydra :remove: not ready
https://github.com/lidashuang/github_oauth :remove: barely started
https://github.com/aaronrenner/phx_gen_auth :remove: merged with phoenix
https://github.com/cpjk/canary
https://github.com/lycus/exmake :remove: hopelessly out of date
https://github.com/SpotIM/gen_spoxy :remove: deprecated
https://github.com/wooga/locker :remove: hopelessly out …
```
> Remove archived repos from the list

- README.md
This adds Once More library I've recently published.
> Add once_more library

- README.md
This adds Honeybadger to the Exception Handling section, and also updates the "Logging" description to be more specific. Thanks!
> Add Honeybadger to Exception Handling

- README.md
Ash AI was recently released at ElixirConfEU Krakow 2025, adding it to the AI section.
> Add Ash AI to AI section
